refactor some lower level utils

diff --git a/qqX b/qqX
--- a/qqX
+++ b/qqX
@@ -64,10 +64,11 @@ fi
 
 # # This script:   major.minor.point[.dev-point]  x.x.2dp[.2dp]  where x = any whole number and the last register always being 2dp.
 # The 2nd register becomes printf'ed to 2dp for upgrade valuation while a single 0 in the third register indicates beta  [with fourth register at 2dp]
-ModVersion="1.7.01"
+qqX_Version="1.7.01"
 
-if [[ "$(basename "$0")" != "qqX" ]]; then echo; echo "Main File Name ERROR"; echo exit 1 ; fi   # check name is okay   
-
+# Check name is okay. qqX but also lc qqx symlink.
+if [[ "$(basename "$0")" == "qqX" ]] || [[ "$(basename "$0")" == "qqx" ]]; then true; else echo; echo "Main File Name ERROR"; echo; exit 1 ; fi   
+  
 ## Dev: Set =1 to stop (and pause 1 sec), for easier fault tracing. Set =integer for add longer pauses. Use "0.2" etc for less.
 NoClear=
 GeneralLoopCheck=  
@@ -148,7 +149,6 @@ if grep -q -s -e 'echo 38 39' "$QG_FilePath" ; then
   [[ $QE_VerNumber == "4.9.1" ]] && QE_VerNumber="4.9.2"
 
 fi
-
 
 function main_menu {
 
diff --git a/qqX.main/qqX_Initialize b/qqX.main/qqX_Initialize
--- a/qqX.main/qqX_Initialize
+++ b/qqX.main/qqX_Initialize
@@ -172,7 +172,7 @@ if [[ $1 == "XDG" ]]; then
 
   fi
 
-elif [[ $1 == "--version" || $1 == "-V" ]] ; then  echo "$ModVersion" ; exit 
+elif [[ $1 == "--version" || $1 == "-V" ]] ; then  echo "$qqX_Version" ; exit 
 
 elif [[ "$1" == *'vm' ]] && [[ $2 == *'.conf' ]]; then  
 
@@ -190,37 +190,23 @@ else
 fi
 
 
-#  Pick up the SETTINGS file: 
+#  Pick up the SETTINGS file 
+#  qqX version 1.7 starts on the removal of legacy 'qwrap' code lines and introduces a custom settings file
 
-#  qqX version 1.7 starts on the removal of legacy 'qwrap' code lines. 
-#  A possibilty to have a local 'dev' version setting file is retained.  May be .dot hidden or plain
+if [[ ! -f "$HOME/.qqX/qqX_settings" ]]; then 
 
-[[ -e "$HOME/.qqX/qqX_settings" ]] && qqX_SettingsFile="$HOME/.qqX/qqX_settings"
+  printf "\n\n  ERROR with settings file detection \n\n  Re-check Installation &/or Installation instructions \n\n" ; sleep 10 ; exit 1
 
+else
 
-if [[ -e "$qqX_SettingsFile" ]]; then  source "$qqX_SettingsFile" 
-
-elif [[ -e "$CurrentFolder/qqX_settings" ]] && [[ "$CurrentFolder" != '/usr'* ]]; then  
-
-  qqX_SettingsFile="$CurrentFolder/qqX_settings" ; source "$qqX_SettingsFile" 
-
-elif [[ -e "$CurrentFolder/.qqX_settings" ]] && [[ "$CurrentFolder" != '/usr'* ]]; then  
-
-  qqX_SettingsFile="$CurrentFolder/.qqX_settings" ; source "$qqX_SettingsFile" 
-  
-else  printf "\n\n  ERROR with settings file detection \n\n  Re-check Installation &/or Installation instructions \n\n" ; sleep 10 ; exit 1
-  
-fi
-
-
-if [[ $AllowMoreLocale ]]; then
-
-  export "LC_NUMERIC=C"
-  export "LC_COLLATE=C"
-
-else  export "LC_ALL=C"
+  qqX_SettingsFile="$HOME/.qqX/qqX_settings"
+  source "$qqX_SettingsFile" 
+  [[ -f "$HOME/.qqX/custom_settings" ]] && source "$HOME/.qqX/custom_settings"
 
 fi
+
+if [[ $AllowMoreLocale ]]; then export "LC_NUMERIC=C" ; export "LC_COLLATE=C" ; else  export "LC_ALL=C" ; fi
+
 
 # Determine possible XDG folders 
 
