add folder qqX.lib  and add to  PATH,  move floatversion to lib

diff --git a/qqX b/qqX
--- a/qqX
+++ b/qqX
@@ -91,6 +91,7 @@ function path_diagnostics {
     echo; echo "Export PATH = $PATH"
     echo; echo "qqX_MainFolder: $qqX_MainFolder"
     echo "qqX_BuiltinsFolder: $qqX_BuiltinsFolder"
+    echo "qqX_LibraryFolder: $qqX_LibraryFolder"
     echo "qqX_CustomFolder: $qqX_CustomFolder"
     echo "XDG_GUI_desktop_Folder: $XDG_GUI_desktop_Folder"
     echo; echo "FreePath = $FreePath  QE_SystemFilePath = $QE_SystemFilePath"
@@ -121,6 +122,9 @@ if [[ ! -d "$qqX_MainFolder" ]]; then echo; echo "  ERROR: qqX main files not fo
 
 if [[ -d "./qqX.builtins" ]]; then qqX_BuiltinsFolder="$(realpath "./qqX.builtins")" ; else qqX_BuiltinsFolder="/usr/share/qqX/qqX.builtins"; fi
 if [[ ! -d "$qqX_BuiltinsFolder" ]]; then echo; echo "  ERROR: qqX builtin files not found.  Please re-check your installation."; echo; sleep 10; exit 1 ; fi
+
+if [[ -d "./qqX.lib" ]]; then qqX_LibraryFolder="$(realpath "./qqX.lib")" ; else qqX_LibraryFolder="/usr/share/qqX/qqX.lib"; fi
+if [[ ! -d "$qqX_LibraryFolder" ]]; then echo; echo "  ERROR: qqX library not found.  Please re-check your installation."; echo; sleep 10; exit 1 ; fi
 
 # Read secure folder for custom user scripts, which should be admin safe eg. "/usr/share/qqX/qqX.custom"
 qqX_CustomFolder="$(dirname "$qqX_MainFolder")""/qqX.custom"
@@ -160,11 +164,6 @@ ConfClearanceLog="/tmp/qqX_ConfClearance_Log.txt"
 source "$qqX_MainFolder/qqX_Initialize"
 source "$qqX_MainFolder/qqX_read_main_settings"
 source "$qqX_MainFolder/qqX_UI_chrome_up"
-
-# Ver 1.11.0  add  'floatversion'  and  wrapper function to call it
-floatversion () { 
-  "$qqX_MainFolder/floatversion" "$@" 
-}
 
 [[ $GeneralLoopCheck ]] && printf "\n\n QE_SourcePath = %s \n\n QG_SourcePath = %s \n"  "$QE_SourcePath" "$QG_SourcePath"
 
diff --git a/qqX.lib/floatversion b/qqX.lib/floatversion
--- a/qqX.lib/floatversion
+++ b/qqX.lib/floatversion
@@ -200,7 +200,7 @@ float_version_from_string ()  {
           printf "\n  ERROR:  '%s'  not recognised \n" "$1" >&2
           show_help >&2 ; return 1
         elif [[ $InputText ]]; then
-          printf "\n  ERROR: QUOTED Input String or Text File Name should be given only once \n" >&2
+          printf "\n  ERROR: QUOTED Input String or Text File Name should be given \n" >&2
           show_help >&2 ; return 1
         else
           InputText="$1" ; shift 
@@ -223,8 +223,7 @@ float_version_from_string ()  {
   fi
 
   if [[ ! $InputText ]]; then 
-    { printf "\n  ERROR: no input found?"
-      printf "\n  Input data should be piped or presented as a quoted element"
+    { printf "\n  Input data should be piped or presented as a quoted element"
       printf "\n  To suppress empty pipe errors use '2>/dev/null' \n"
     } >&2
     show_help >&2 ; return 1
