add more modules (testing) but appears okay

diff --git a/qqX b/qqX
--- a/qqX
+++ b/qqX
@@ -82,10 +82,12 @@ fi
 ModVersion="1.7.01"
 
 ModName="$(basename "$0")"
-if [[ $ModName == "qqx" || $ModName == "qqX" ]]; then ModName_qqX=1 ; else  ModName_qqX=  ; fi    # deprecated
+if [[ $ModName != "qqX" ]]; then echo; echo "Main File Name ERROR"; echo exit 1 ; fi   # check name is okay   
+
+#  TODO  ModName  %s  printf remove deprecated usages
 
 #  Screen clears; set =1 to stop (and pause 1 sec), for easier fault tracing. Set =integer for add longer pauses. Use "0.2" etc for less.
-NoClear="0.1"
+NoClear=1
 
 #  CODING STYLE 
 
@@ -180,6 +182,8 @@ source "$qqX_MainFolder/qqX_quick_reroute_get"
 
 source "$qqX_MainFolder/qqX_configuration_items"
 
+source "$qqX_MainFolder/qqX_VM_selector_styles"
+
 source "$qqX_MainFolder/qqX_VM_array_and_Select"
 
 source "$qqX_MainFolder/qqX_disk_maintenance"
@@ -193,88 +197,44 @@ source "$qqX_MainFolder/qqX_main_menu_interface"
 source "$qqX_MainFolder/qqX_main_menu_actions"
 
 
-##  START:  QUICKEMU-WRAP  menu interface  &  API DIVIDER  ###
+function main_menu {
 
-#   NB   Also see initial $1 flag setting traps   &&  TODO   qwrap is now deprecated  
+  while true ; do
 
-if [[ $1 ]]; then
+    MainMenuChoice=
+    SnapTitle=
+    SnapNumber=
+    SnapName=
 
-  # simple API for command line or .conf starts  ie.  --vm  "path/folder/file.conf"   
+    show_main_menu_header
 
-  if [[ $XDG_QcowRightClick ]]; then
+    if [[ $KillPID_Menu_Exited ]] ; then
 
-    # should haved changed to the parent directory at this point
+      if [[ $InstancePID ]] && [[ $( ps -p "$InstancePID" --no-headers ) ]] && [[ $(cat "${VMDIR}/${VMNAME}.pid" 2> /dev/null) ]]; then 
+        printf "\n\n  %s is still running ..." "$VM_InstanceName" ; vm_pid_kill_menu ; continue
+      else  InstancePID= ;  printf "\n    %s   >   is now shut down  >  select restart or manage \n" "$VM_InstanceName" 
+      fi
 
-    if grep -q -s "disk_img="'"'"$XDG_QcowRightClick_VM_Dir_Name/$XDG_QcowRightClick_DiskName" "$XDG_QcowRightClick_VM_Dir_Name.conf" ; then
-
-      VM_Conf_Dir="$(pwd)"
-      VM_Conf_File="$XDG_QcowRightClick_VM_Dir_Name.conf"
-      VM_InstanceName="$XDG_QcowRightClick_VM_Dir_Name"
-      shift
-
-    else  XDG_QcowRightClick_NO_qqX=1 ; shift
+      [[ $KillPID_Menu_Exited ]] && KillPID_Menu_Exited=  
+      [[ $UseCustomBootArgs ]] && UseCustomBootArgs=  
 
     fi
 
-  elif [[ $XDG_StartVariant ]]; then
+    [[ ! $MainMenuChoice ]] && main_menu_interface
 
-    echo
-    function_qqX_logo
-    printColor "\n\n  %s  not understood \n\n  Or non valid file type %s \n\n"  "$1 "  "$XDG_MimeType"
-    sleep 5 
-
-  elif [[ "$1" == *'vm' ]] && [[ "$2" == *'.conf' ]]; then
-
-    # conforms to  -vm | --vm  file.conf
-    VM_Conf_Dir="$(dirname "$2")"
-    VM_Conf_File="$(basename "$2")"
-    shift $#
-
-  else 
-  
-    show_wrap_CLI_usage 
-    printf "\n\n"
-    exit directly
-
-  fi
-
-  # only $1 starts
-
-  if [[ ! $VM_Conf_Dir ]]; then  VM_Conf_Dir="$CurrentFolder"
-
-  else
-
-    if [[ ! -e  "$VM_Conf_Dir"  ]]; then 
-
-      printColor "\n\n  %s  not found "  "$VM_Conf_Dir "
+    main_menu_actions
     
-      function_conf_error  " COMMAND LINE Path Instruction,"
+    [[ ! $VM_InstanceName ]] && break
 
-    else  cd "$VM_Conf_Dir"  || function_conf_error  " COMMAND LINE Path Instruction,"
+  done
 
-    fi
+} 
 
-  fi
-
-  if [[ ! -e "$VM_Conf_Dir/$VM_Conf_File" ]]; then 
-
-    printColor "\n\n  %s  not found "  "$VM_Conf_File"
-  
-    function_conf_error  " COMMAND LINE .Conf Instruction,"
-
-  fi
-
-   # Selection now made, but array must still be loaded as may be needed for reselecting later ...
-   ByPass_VM_Array_Selector=1
-
-fi
-
-
-##  General pre-menu checks  
+##  General pre-menu-loop checks  
 
 tput civis
 printf "\033c"
-show_qmod_title
+show_qqX_title_bar
 
 printf "\n  Running initial checks .... \n"
 
@@ -288,88 +248,21 @@ if [[ ! $Disable_qqX_upd_Checks ]]; then
 fi
 
 
+#  '$1' Check any MOUSE CLICK or COMMAND LINE parameters and read any flags set during 'qqX_initialize' 
+#  General format is  --vm  "path/folder/file.conf", including .desktop starts which will have originally had 'XDG' as $1
 
-## MAIN MENU  
+if [[ $1 ]]; then source "$qqX_MainFolder/qqX_api_and_mouse_tidyup" ; fi
 
-function main_menu {
-
-  while true ; do
-
-    MainMenuChoice=
-    SnapTitle=
-    SnapNumber=
-    SnapName=
-
-    show_main_menu_header
-
-    if [[ $XDG_QcowRightClick_NO_qqX ]] || [[ $XDG_QcowRightClick ]]; then
-
-      check_disk_is_okay "$XDG_QcowRightClick_VM_Dir_Name"  "$XDG_QcowRightClick_DiskName"
-
-      if [[ $DiskChkStatus ]] && [[ $DiskChkStatus != "Okay" ]]; then printColor "\n\n DISK.QCOW2 ERROR  %s "  "$DiskChkStatus" ; fi
-
-      if [[ $XDG_QcowRightClick_NO_qqX ]]; then 
-        
-        [[ $DiskChkStatus == "Okay" ]] && printColor  "\n\n QEMU qcow2 disk found BUT not configured as qqX/quickemu bootable: \n\n"
-
-      else
-        
-        printColor  "\n\n  qqX/quickemu bootable: \n\n"
-
-        if [[ $DiskChkStatus != "Okay" ]]; then  
-          printColor "  BUT has errors: Try qqX [disk] utils " 
-          printf "\n\n Also see  https://qemu.readthedocs.io  "
-          printf  "> QEMU disk image utility notes\n\n"
-        fi
-
-      fi
-
-      "$QEMU_IMG" info "$XDG_QcowRightClick_VM_Dir_Name/$XDG_QcowRightClick_DiskName"
-          
-      if [[ $XDG_QcowRightClick_NO_qqX ]]; then  
-
-        printColor "\n\n See  https://qemu.readthedocs.io  "
-        printf  "> QEMU disk image utility may be useful"
-        printf "\n\n  [enter] to quit  "
-        
-      else  printColor "\n\n  [enter] to continue  "
-        
-      fi
-
-      read -rp  "  >  "
-      
-      if [[ ! $XDG_QcowRightClick_NO_qqX ]]; then XDG_QcowRightClick=  ; show_main_menu_header
-      else  exit directly 
-      fi
-
-    elif [[ $KillPID_Menu_Exited ]] || [[ $Select_VM ]] ; then
-
-      if [[ $InstancePID ]] && [[ $( ps -p "$InstancePID" --no-headers ) ]] && [[ $(cat "${VMDIR}/${VMNAME}.pid" 2> /dev/null) ]]; then 
-        printf "\n\n  %s is still running ..." "$VM_InstanceName" ; vm_pid_kill_menu ; continue
-      else  InstancePID= ;  printf "\n    %s   >   is now shut down  >  select restart or manage \n" "$VM_InstanceName" 
-      fi
-
-      [[ $KillPID_Menu_Exited ]] && KillPID_Menu_Exited=  
-      [[ $UseCustomBootArgs ]] && UseCustomBootArgs=  
-
-    fi
-
-    main_menu_interface
-    main_menu_actions
-
-    if [[ ! $VM_InstanceName ]];  then break ; fi 
-
-  done
-
-  # end of main menu
-
-}
+# Selection now possibly have been made via api or mouse, but array must still be loaded as may be needed for reselecting later ...
+[[ $VM_InstanceName ]] && ByPass_VM_Array_Selector=1
 
 
 # Dev
-GeneralLoopCheck=   
+GeneralLoopCheck=1   
 
 tput civis
+
+## MAIN LOOP
 
 while true ; do
 
@@ -382,13 +275,18 @@ while true ; do
     # sleep 1
   fi
 
-  if [[ ! $VM_InstanceName ]]; then vm_selector_menu
+  # Where 'ByPass_VM_Array_Selector' implies run the loader section only (eg. XDG and .conf clicked starts)
 
-  else  main_menu  ; fi
+  if [[ ! $VM_InstanceName || $ByPass_VM_Array_Selector ]]; then  VM_loader_selector_and_menu
+
+  else   main_menu 
+  
+  fi
 
 done
 
 tput  cnorm
+
 
 # https://code.visualstudio.com/  (recommended)
 
diff --git a/qqX.main/qqX_Initialize b/qqX.main/qqX_Initialize
--- a/qqX.main/qqX_Initialize
+++ b/qqX.main/qqX_Initialize
@@ -24,6 +24,17 @@
 #  shellcheck disable=SC2154 
 
 
+qqX_logo_plain() {
+  
+  # early loader 
+
+  echo "  _    _   \/   "
+  echo " (_|  (_|  /\ "
+  echo "   |.   |.    "
+
+}
+
+
 if  [[ $NoClear ]]; then 
 
 	printf () {
@@ -78,30 +89,82 @@ if [[ ! $(type -p curl) ]] || [[ ! $(type -p aria2c) ]] || [[ ! $(type -p zsync)
   if [[ $1 ]]; then exit 1 ; else read -rp "  [enter] to continue > " ; fi
 fi
 
-if [[ $1 == "XDG" ]]; then 
 
-  # set xdg flags for now, deal with details after the basic initializing is done
+#  Check any MOUSE CLICK or COMMAND LINE parameters and set any initial flags
+#  Further processing is done in the 'qqX_api_and_mouse_tidyup' script, after other functions have been loaded
+
+echo "$@"  ; echo   #   TEMP 
+
+if [[ $1 == "XDG" ]]; then 
 
   if [[ -e "$2" ]]; then
 
     XDG_MimeType="$(mimetype "$2" 2>/dev/null)"
    
-    if [[ "$XDG_MimeType" == *'application/x-qemu-disk' ]]; then XDG_MimeType_Valid=1
+    if [[ "$XDG_MimeType" == *'application/x-qemu-disk' ]]; then XDG_MimeType_is_QCOW=1
 
-    else XDG_MimeType_Valid=  ; fi
+    elif [[ "$XDG_MimeType" == *'text/plain' ]] &&  grep -q -s 'guest_os' "$2" ; then 
+    
+     QCOW_RightClick= #1 ; shift 
+
+      #hideme () {
+      echo "$@"  ; echo   #   TEMP 
+
+        # conforms to  -vm | --vm  file.conf
+        VM_Conf_Dir="$(dirname "$2")"
+        [[ "$VM_Conf_Dir" == '.' ]] && VM_Conf_Dir="$(pwd)"
+        VM_Conf_File="$(basename "$2")"
+        VM_InstanceName="${VM_Conf_File/'.conf'/}"
+        shift $#
+
+      #}
+
+    elif [[ "$XDG_MimeType" == *'text/plain' ]] ; then
+    
+      QCOW_RightClick= 
+      XDG_MimeType_is_QCOW=  
+      QCOW_RightClick_Conf_Dir=
+      echo
+      qqX_logo_plain
+      echo; echo " $2"; echo
+      echo " qqX has been associated to open .conf (text) files via the file properties 'open-with' option."
+      echo; echo; echo "<<" 
+      head -20 "$2"
+      echo ">>" ; echo
+      FileLines="$(wc -l < "$2")"
+      printf "\n This current file is plain text only. " 
+      [[ $FileLines -gt 20 ]] && printf " File length %s lines \n"  "$FileLines"  &&  TextAll="[a] view full text & quit   "
+      echo
+      echo " [enter] to run qqX   $TextAll [q]  quit"
+      echo
+      read -rp " >  "   ConfOpener
+      echo  
+
+      if [[ $ConfOpener == "a" ]]; then  cat "$2"; echo; echo " [enter] to quit  "; echo; read -rp " >  "; exit 
+      elif [[ $ConfOpener == "q" ]]; then exit
+      else VM_InstanceName= ; XDG_MimeType_Recognised=1
+      fi
+
+    else
+
+      XDG_StartVariant=1
+      XDG_MimeType_Recognised=
+      XDG_MimeType_is_QCOW=  
+      
+    fi
 
   fi
 
-  if [[ $XDG_MimeType_Valid ]]; then
+  if [[ $XDG_MimeType_is_QCOW ]]; then
 
-    # is a right-click start on a qcow2 disk (set flag for later) 
-    XDG_QcowRightClick=1
+    # is a right-click start on a qcow2 disk (flag is set for later)  
     shift
     
   elif [[ $2 ]]; then
 
-    # is right click XDG but at this stage needs flagging for later analysis or other type of handling
+    # is right click XDG but at this stage needs flagging for later analysis or other type of handling 
     XDG_StartVariant=1
+    XDG_MimeType_is_QCOW= 
     shift
 
   else
@@ -115,16 +178,35 @@ if [[ $1 == "XDG" ]]; then
   fi
 
 
-elif [[ $ModName_qqX ]] && [[ $1 == "--version" || $1 == "-V" ]] ; then  echo "$ModVersion" ; exit 
+elif [[ $1 == "--version" || $1 == "-V" ]] ; then  echo "$ModVersion" ; exit 
 
 
-elif [[ ! $ModName_qqX ]] && [[ "$1" == *'vm' ]]; then  
+elif [[ "$1" == *'vm' ]]; then   #  FIXME 
 
-  # quickemu-wrap only  &  where test [[ $Conf_TriggerFolder ]] will also flag up if the script was .conf target started
+#shift
+echo "$@"  ; echo
 
-  Conf_TriggerFolder="$(dirname "$0")"
-  
-  CurrentFolder="$(dirname "$2")"
+#VM_Conf_File="$(basename "$2")"
+#VM_InstanceName="${VM_Conf_File/'.conf'/}"
+#VM_Conf_Dir="$(dirname "$2")"
+#[[ "$VM_Conf_Dir" == '.' ]] && VM_Conf_Dir="$(pwd)"
+
+        # conforms to  -vm | --vm  file.conf
+        VM_Conf_Dir="$(dirname "$2")"
+        [[ "$VM_Conf_Dir" == '.' ]] && VM_Conf_Dir="$(pwd)"
+        VM_Conf_File="$(basename "$2")"
+        VM_InstanceName="${VM_Conf_File/'.conf'/}"
+        shift $#
+
+
+echo "VM_InstanceName = $VM_InstanceName"
+
+echo "VM_Conf_File = $VM_Conf_File"
+
+echo "VM_Conf_Dir = $VM_Conf_Dir"
+
+sleep 3    #   TEMP  
+
 
 else 
 
@@ -132,67 +214,28 @@ else
   
 fi
 
-#  Pick up the SETTINGS file:  If placing the main file in /usr/bin,"
-#  then place the settings file as "/$HOME/.qmod_settings, OR if qqX in "/$HOME/.qqX/qqX_settings"
-
-#  For details, see notes at start of the settings file ...
-
-#  Use full quoted path & name if adding in a additional folder to this script or different to these defaults
-#  For .conf click starts, the Positional parameters need reading to check the settings file location;
-#  this would be expected to be where the specified wrap script is located as a first check
 
 
-if [[ $ModName_qqX ]]; then SettingsName="qqX_settings"
+#  Pick up the SETTINGS file: 
 
-else SettingsName="qmod_settings" ; fi
+#  qqX version 1.7 starts on the removal of legacy 'qwrap' code lines. 
+
+#  A possibilty to have a local 'dev' version setting file is retained.  May be .dot hidden or plain
+
+[[ -e "$HOME/.qqX/qqX_settings" ]] && qqX_SettingsFile="$HOME/.qqX/qqX_settings"
 
 
-if [[ $ModName_qqX ]]; then 
+if [[ -e "$qqX_SettingsFile" ]]; then  source "$qqX_SettingsFile" 
 
-  [[ -e "$HOME/.qqX/qqX_settings" ]] && Q_Mod_SettingsFile="$HOME/.qqX/qqX_settings"
+elif [[ -e "$CurrentFolder/qqX_settings" ]] && [[ "$CurrentFolder" != '/usr'* ]]; then  
 
-#
+  qqX_SettingsFile="$CurrentFolder/qqX_settings" ; source "$qqX_SettingsFile" 
 
-elif [[ $Conf_TriggerFolder ]] && [[ -e "$Conf_TriggerFolder/${SettingsName}" ]]; then  
+elif [[ -e "$CurrentFolder/.qqX_settings" ]] && [[ "$CurrentFolder" != '/usr'* ]]; then  
 
-  Q_Mod_SettingsFile="$Conf_TriggerFolder/${SettingsName}"
-
-#
-
-elif [[ -e "$CurrentFolder/${SettingsName}" ]] && [[ "$CurrentFolder" != '/usr'* ]]; then  
-
-  Q_Mod_SettingsFile="$CurrentFolder/${SettingsName}"
-
-elif [[ -e "$CurrentFolder/.${SettingsName}" ]] && [[ "$CurrentFolder" != '/usr'* ]]; then  
-
-  Q_Mod_SettingsFile="$CurrentFolder/.${SettingsName}"
-
-#  
-
-elif [[ -e "$HOME/.qmod_settings" ]] && [[ ! $ModName_qqX ]] ; then  
-
-  Q_Mod_SettingsFile="$HOME/.qmod_settings"
-
-elif [[ -e "$HOME/qmod_settings" ]] && [[ ! $ModName_qqX ]] ; then 
-
-  Q_Mod_SettingsFile="$HOME/qmod_settings"
-
-else  
-
-  Q_Mod_SettingsFile=  
-
-  echo; echo "  No settings file found .... " ; echo ; sleep 2
+  qqX_SettingsFile="$CurrentFolder/.qqX_settings" ; source "$qqX_SettingsFile" 
   
-fi
-
-
-if [[ -e "$Q_Mod_SettingsFile" ]]; then
-    
-  if [[ $ModName_qqX ]]; then source "$Q_Mod_SettingsFile" ; else source "$Q_Mod_SettingsFile"  QWRAP ; fi
-
-else 
-
-  printf "\n\n  ERROR with settings file detection \n\n  Re-check Installation &/or Installation instructions \n\n" ; sleep 10 ; exit 1
+else  printf "\n\n  ERROR with settings file detection \n\n  Re-check Installation &/or Installation instructions \n\n" ; sleep 10 ; exit 1
   
 fi
 
@@ -211,18 +254,15 @@ fi
 function_xdg_start_folder () {
 
   #  For a .desktop start, to be run after the settings file has been loaded so that a $Default_VM_Folder can be available
-  #  Also can be called (belt & braces) at the other command line $1 trap towards end of script ...  REVIEW 
 
   if [[ ! $(ls "$HOME/"*.conf 2> /dev/null) ]] && [[ -d "$Default_VM_Folder" ]]; then
 
     cd "$Default_VM_Folder"  || printf "\n\n XDG .desktop starter  >  Default_VM_Folder not found " 
-
     CurrentFolder="$Default_VM_Folder"
 
   else
 
     cd "$HOME"  || printf "\n\n XDG .desktop starter  >  HOME Folder not found " 
-
     CurrentFolder="$HOME"
 
   fi
@@ -233,19 +273,23 @@ function_xdg_start_folder () {
 [[ $XDG_GeneralDesktopStart ]] &&  function_xdg_start_folder
 
 
-if [[ $XDG_QcowRightClick ]]; then
+if [[ $XDG_MimeType_is_QCOW ]]; then
 
-  XDG_QcowRightClick_Conf_Dir="$(dirname "$1")"
-  XDG_QcowRightClick_DiskName="$(basename "$1")"
-  XDG_QcowRightClick_VM_Dir_Name="$(basename "$XDG_QcowRightClick_Conf_Dir")"
+  QCOW_RightClick_Conf_Dir="$(dirname "$1")"
+  [[ "$QCOW_RightClick_Conf_Dir" == '.' ]] && QCOW_RightClick_Conf_Dir="$(pwd)"
 
+  QCOW_RightClick_DiskName="$(basename "$1")"  
+  
+  QCOW_RightClick_VM_Dir_Name="$(basename "$QCOW_RightClick_Conf_Dir")"
+ 
   # .desktop starts tend to open in the $HOME folder even if right clicking somewhwere else
+  #  standard right-click open-with actions will use the current folder
 
-  cd "$XDG_QcowRightClick_Conf_Dir" || printf "\n\n XDG .desktop starter  >  Disk's start Folder not found " 
+  cd "$QCOW_RightClick_Conf_Dir" || printf "\n\n XDG .desktop starter  >  Disk's start Folder not found " 
 
   cd ..  || printf "\n\n XDG .desktop starter  >  Disk's root Folder not found " 
 
-  CurrentFolder="$XDG_QcowRightClick_Conf_Dir"
+  CurrentFolder="$QCOW_RightClick_Conf_Dir"
 
 fi
 
