MSR functions to main

diff --git a/qqX b/qqX
--- a/qqX
+++ b/qqX
@@ -156,18 +156,18 @@ if [[ $ModName == "qqx" || $ModName == "qqX" ]]; then ModName_qqX=1 ; else  ModN
 
 # Find where the main code is. Use local for Dev or Custom installs. Otherwise use FHS standard locations.
 
-if [[ -d "qqX.main" ]]; then qqX_MainFolder="$(realpath "qqX.main")"
+qqX_MainFolder="/usr/share/qqX/qqX.main"
 
-elif [[ -d "/usr/share/qqX/qqX.main" ]]; then qqX_MainFolder="/usr/share/qqX/qqX.main"
+[[ -d "./qqX.main" ]] &&  qqX_MainFolder="$(realpath "./qqX.main")"
 
-else  echo; echo "  ERROR: qqX main files not found.  Please re-check your installation."; echo; sleep 10; exit 1
+if [[ ! -d "$qqX_MainFolder" ]]; then 
+
+  echo; echo "  ERROR: qqX main files not found.  Please re-check your installation."; echo; sleep 10; exit 1
 
 fi
 
 
 ## INITIALIZE
-
-# ARRAYS & VARS
 
 # Declare global associative VM ARRAY & other initializing global vars. Make ready to read settings.
 declare -gA VM_Array=()
@@ -184,7 +184,7 @@ ConfClearanceLog="/tmp/qqX_ConfClearance_Log.txt"
 [[ ! -e "$ConfClearanceLog" ]] && printf "" > "$ConfClearanceLog"
 
 
-# LOAD qqX main COMPONENTS 
+# LOAD qqX main  
 
 source "$qqX_MainFolder/qqX_Initialize"
 
@@ -192,355 +192,9 @@ source "$qqX_MainFolder/qqX_read_main_settings"
 
 source "$qqX_MainFolder/qqX_UI_chrome_up"
 
+source "$qqX_MainFolder/qqX_MSR_functions"
 
 
-
-## QMOD MSRS FUNCTIONS  (may also be called via the Mod API)  
-
-find_kvm_msr_default_and_status () {
-
-  # Gives values to VARIABLES: 'KVM_MSR_DefaultConf' & 'KVM_MSR_status' as Y or N 
-
-  # Finds and flags if MSRS has a config conflict for use by function 'print_kvm_status_warnings' & other
-
-  KVM_MSR_Error=
-  KVM_MSR_Warn=
-
-  KVM_MSR_status="$(cat /sys/module/kvm/parameters/ignore_msrs)"
-
-  [[ ! $KVM_MSR_ModProbeFile ]] && KVM_MSR_ModProbeFile="/etc/modprobe.d/kvm-quickemu.conf"
-
-  KVM_MSR_DefaultConf="$(cat "$KVM_MSR_ModProbeFile" 2> /dev/null)"
-
-  [[ "$KVM_MSR_DefaultConf" == *'=Y' ]] &&  KVM_MSR_default="Y"
-
-  [[ "$KVM_MSR_DefaultConf" == *'=N' ]] || [[ ! -e "$KVM_MSR_ModProbeFile" ]] &&  KVM_MSR_default="N"
-
-  if [[ $VM_InstanceName ]]; then
-  
-    if [[ "$VM_InstanceName" == *windows*  ]] ||	[[ "$VM_InstanceName" == *macos*  ]] ; then
-
-      if [[ $KVM_MSR_status == "N" ]]; then KVM_MSR_Error=1 ; else KVM_MSR_Error= ; fi
-
-    elif [[ "$VM_InstanceName" != *windows*  ]] &&	[[ "$VM_InstanceName" != *macos*  ]] ; then
-
-      if [[ $KVM_MSR_status == "Y" ]]; then KVM_MSR_Warn=1 ; else KVM_MSR_Warn= ; fi
-
-    fi
-
-  fi
-}
-
-print_kvm_status_warnings () {
-
-  find_kvm_msr_default_and_status
-
-  if [[ $VM_InstanceName ]]; then
-
-    if [[ $KVM_MSR_Warn ]] && [[ $Verbose_MSR_dialog || $MSR_Warnings ]] || [[ ! $MSR_Warnings && $ShowUtilsMenu ]] ; then 
-    
-    Show_MSR_Warnings=1 ; else Show_MSR_Warnings= ; fi
-
-    if [[ $KVM_MSR_status == "Y" ]] ; then  
-    
-      [[ $KVM_MSR_Error || $Show_MSR_Warnings ]] && printf "\n  /sys/module/kvm/parameters/ignore_msrs  = Y" 
-
-      if  [[ $KVM_MSR_Error ]]; then  printColor "  ERROR \n" 
-
-      elif [[ $Show_MSR_Warnings ]]; then printf "  WARNING \n" ; fi
-      
-    else 
-
-      [[ $KVM_MSR_Error || $Show_MSR_Warnings ]] && printf "\n  /sys/module/kvm/parameters/ignore_msrs  = N" 
-
-      if [[ $KVM_MSR_Error ]]; then printColor "  ERROR \n" 
-
-      elif [[ $Show_MSR_Warnings ]] ; then printf "  WARNING \n" ; fi
-
-    fi
-
-  fi
-
-}
-
-
-toggle_msr_defaults () {
-
-  # Modded & now reversible rewrite of original quickemu's function 'ignore_msrs_always'
-
-  Verbose_MSR_dialog=1
-
-  # https://www.linux-kvm.org/page/Category:Docs
-
-  if [[ ! -d /etc/modprobe.d ]]; then
-
-    printf "\n  ERROR! /etc/modprobe.d was not found. \n\n  See notes, it may be possible to manually create modprobe.d/kvm-quickemu.conf \n\n"
-
-  else
-
-    printColor "\n\n  Configure default, boot-up, KVM behaviour "
-    
-    printf "for unhandled machine-specific registers "
-
-    printf "\n\n  Although the normal Linux setting is N, both Windows and MacOS require Y (true) 'ignore'"
-
-    printf "\n\n  But as Linux distros can generally use either, set to Y if Windows or MacOS are present."
-
-    find_kvm_msr_default_and_status
-    printf "\n\n  Status:  /sys/module/kvm/parameters/ignore_msrs = %s   Current Default = %s"   "$KVM_MSR_status"  "$KVM_MSR_default"
-
-    [[ ! $KVM_MSR_ModProbeFile ]] && KVM_MSR_ModProbeFile="/etc/modprobe.d/kvm-quickemu.conf"
-
-    if [[ ! -e "$KVM_MSR_ModProbeFile" ]]; then  printf "\n\n  \'%s\'  needs to be created "  "$KVM_MSR_ModProbeFile" 
-
-    fi
-
-    printf "\n\n  [y] to set Y  [n] to set N  [b] to go back \n\n"
-
-    read -rp  "  > "  Set_MSR_defaults
-
-    # set .conf file content & update initramfs in all kernels (y/n or none)
-
-    if [[ $Set_MSR_defaults == "y" ]]; then
-
-      printf "\n\n  Updating 'initramfs' may take a moment or two ... \n\n"
-
-      # As per Martin's solution in original quickemu, needs 'tee' to get this to work, 
-      # but route tee's stdout to null to tidy the screen 
-
-      echo "options kvm ignore_msrs=Y" | sudo tee "$KVM_MSR_ModProbeFile" 1> /dev/null
-      sudo update-initramfs -k all -u
-
-    elif [[ $Set_MSR_defaults == "n" ]]; then
-
-      printf "\n\n  Updating 'initramfs' may take a moment or two ... \n\n"
-
-      echo "options kvm ignore_msrs=N" | sudo tee "$KVM_MSR_ModProbeFile" 1> /dev/null
-      sudo update-initramfs -k all -u
-
-    fi
-
-    find_kvm_msr_default_and_status
-    printf "\n\n  Status:  /sys/module/kvm/parameters/ignore_msrs = %s   Current Default = %s"   "$KVM_MSR_status"  "$KVM_MSR_default"
-
-    printf "\n\n  A %s may be required"  "$ModName"
-
-  fi
-
-}
-
-
-show_kvm_msr_general_note () {
-
-  printColor "\n  If expecting to use Windows or MacOS, you should modify the system boot settings. "
-  
-  printf   "\n\n  %s has a built in function that can do this for you & allow for future adjustments." "$ModName"
-  
-  printf   "\n\n  "
- 
-  [[ $MSR_DistrosFound ]] &&  printColor "Windows or MacOS distros appear present.  "
- 
-  printf   "See the further notes for details."
- 
-  printColor "\n\n\n  Status:  /sys/module/kvm/parameters/ignore_msrs = %s   Current Default = %s"   "$KVM_MSR_status"  "$KVM_MSR_default"
- 
-  printf "\n\n  Windows or MacOS should be set to 'Y' whilst Linux distros can generally use either."
-
-}
-
-show_kvm_sudo_security_note () {
-
-  printColor "\n  For session adjustments %s requires 'sudo' permissions to echo true or false to 'ignore_msrs'" "$ModName"
-  
-  printf   "\n\n  This allows you to create a temporary MSRS status that may be changed at any time,"
-  
-  printf   "\n\n  allowing you to match the selected guest VM that you want to run."
-
-
-  printf "\n\n\n  Linux distros don't *seem* to be affected when set as true \n\n  but KVM does have a default of false ..."
-
-  printColor "\n\n\n  If you have concerns about this script, or about giving elevated permissions, "
-  
-  printf   "\n\n  then the script should be checked or you should issue these commands manually:"
-
-    printf   "\n\n\n  Use shift-crtl-c (or your distros variant) to copy the displayed sudo command, then"
-  
-  printf   "\n\n  open a side terminal & use shift-crtl-v to paste it.  In this way, elevated permissions"
-  
-  printf   "\n\n  will only exist in the side terminal & will cease as soon as it is closed."
-  
-
-  printf   "\n\n\n  Run the command & close the terminal."
-
-  printf   "\n\n  Return to %s & select 'leave as ...'  The msrs settings will auto-update. "   "$ModName" 
-
-  printf   "\n\n"
-  
-}
-
-
-select_msr_config () {
-
-  # Normally called when MSRS/OS conflict previously detected, 
-  # or if selector is being used to change current status. 
-
-  find_kvm_msr_default_and_status
-  KVM_MSR_selector=
-
-  while true ; do
-
-    [[ $KVM_MSR_selector_LoadHelp ]] && show_kvm_msr_general_note  
-
-    if [[ $MSR_DistrosFound && $KVM_MSR_status == "N" ]]; then
-
-      printf "\n\n  Sudo command to set as Y:  echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs"
-
-      printColor "\n\n  [y] to set session to Y "
-
-      printf "  [enter]  leave as N"
-
-    elif [[ $MSR_DistrosFound && $KVM_MSR_status == "Y" ]]; then
-
-      printf "\n\n  Sudo command to set as N:  echo 0 | sudo tee /sys/module/kvm/parameters/ignore_msrs"
-
-      printColor "\n\n  [enter]  leave as Y "
-
-      printf "  [n] to set session to N"
-
-    elif [[ ! $MSR_DistrosFound && $KVM_MSR_status == "N" ]]; then
-
-      printf "\n\n  Sudo command to set as N:  echo 0 | sudo tee /sys/module/kvm/parameters/ignore_msrs"
-
-      printColor "\n\n  [enter]  leave as N"
-
-      printf "  [y] to set session to Y"
-
-    elif [[ ! $MSR_DistrosFound && $KVM_MSR_status == "Y" ]]; then
-
-      printf "\n\n  Sudo command to set as N:  echo 0 | sudo tee /sys/module/kvm/parameters/ignore_msrs"
-
-      printColor "\n\n  [n] to set session to N "
-
-      printf "  [enter]  leave as Y"
-
-    fi
-    
-    if [[ $KVM_MSR_selector == "h" ]] || [[ $KVM_MSR_selector_LoadHelp ]] ; then 
-    
-      if [[ $FurtherNoteFlag ]]; then FurtherNoteFlag= ; else  printf "   [f] see further notes" ; fi
-      
-      printf "   [d] to set the defaults (on boot up) \n\n"
-
-    else  printf "   [h] see help  \n\n" 
-
-    fi
-    
-    read -rp "  >  "  KVM_MSR_selector
-    
-    printf "\n"
-
-    [[ ! $KVM_MSR_selector ]]  &&  break  
-
-    if [[ $KVM_MSR_selector == "y" ]] || [[ $KVM_MSR_selector == "n" ]]; then   
-
-      # As per the solution in original quickemu, needs 'tee' to get this to work, 
-      # but route tee's stdout to null to tidy the screen  
-
-      [[ $KVM_MSR_selector == "y" ]] &&  echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs  1> /dev/null   
-
-      [[ $KVM_MSR_selector == "n" ]] &&  echo 0 | sudo tee /sys/module/kvm/parameters/ignore_msrs  1> /dev/null  
-
-      find_kvm_msr_default_and_status
-      printf "\n\n  Status:  /sys/module/kvm/parameters/ignore_msrs = %s   Current Default = %s"   "$KVM_MSR_status"  "$KVM_MSR_default"
-
-      printf "\n\n  A %s may be required"  "$ModName"
-
-      printColor "\n\n  [enter]  to return \n\n"
-      read -rp  "  > "
-
-      break
-
-    fi
-
-    if [[ $KVM_MSR_selector == "d" ]]; then
-
-      toggle_msr_defaults  
-
-      if [[ $Set_MSR_defaults == "b" ]]; then 
-      
-        Set_MSR_defaults= 
-        print_kvm_status_warnings
-        printColor "\n\n\n  Make TEMPORARY setting adjustments to MSRS ?"
-
-      else 
-        find_kvm_msr_default_and_status
-        break 
-      fi 
-
-    elif [[ $KVM_MSR_selector == "f" ]]; then
-
-      show_kvm_sudo_security_note
-
-      FurtherNoteFlag=1
-
-    fi
-
-  done
-
-  KVM_MSR_selector=
-  KVM_MSR_selector_LoadHelp=
-
-}
-
-msrs_conflict_check_resolver() {  
-
-  # Do a check ...
-
-  find_kvm_msr_default_and_status
-    
-  # Display & Offer config settings if MSRS/OS CONFLICT exists
-
-  if [[ $KVM_MSR_status == "N" ]] ; then
-
-    # usual system default = N
-
-    if [[ "$VM_InstanceName" == *windows*  ]] ||	[[ "$VM_InstanceName" == *macos*  ]] ; then 
-
-      [[ ! $ByPass_VM_Array_Selector ]] && printf "\033c"
-    
-      printColor "\n\n  Selected: %s "  "$VM_InstanceName"
-      
-      printf " 'ignore_msrs' is set & is recommended for Windows and Mac"  
-
-      select_msr_config
-
-      if [[ $KVM_MSR_status == "N" ]]; then KVM_MSR_Error=1 ; else KVM_MSR_Error= ; fi
-
-    fi
-    
-  else
-
-    #  Status = Y  &  which is recommended for Windows & Mac 
-
-    if [[ "$VM_InstanceName" != *windows*  ]] &&	[[ "$VM_InstanceName" != *macos*  ]] ; then
-
-      [[ ! $ByPass_VM_Array_Selector ]] && printf "\033c"
-
-      printColor "\n\n  Selected: %s "  "$VM_InstanceName"
-    
-      printf "\n\n 'ignore_msrs' is set:  can be okay for other OS's but is normally used only with Windows and Mac"  
-
-      select_msr_config
-
-      if [[ $KVM_MSR_status == "Y" ]]; then KVM_MSR_Error=1 ; else KVM_MSR_Error= ; fi
-
-    fi
-
-  fi
-
-}
-
-#   End of MSRS functions
 
 
 ##  Start ADD-IN of ORIGINAL quickemu functions & the needed variables
