update floatversion

diff --git a/qqX.main/floatversion b/qqX.main/floatversion
--- a/qqX.main/floatversion
+++ b/qqX.main/floatversion
@@ -118,6 +118,8 @@ float_version_from_string ()  {
   local Verbose=
   local UseSortV=
   local NoSortVfallback=
+  local CurrentVersion=
+  local LatestVersion=
   declare -a NumArrTemp 
   declare -a NumArrSorted 
   declare -a FilterArr 
@@ -130,8 +132,20 @@ float_version_from_string ()  {
     case "$1" in 
       -h|--help)  
         show_help ; return 0 ;;
-      -V|--version)  
-        echo "1.0.01" ; return 0 ;;
+      -V|--version)
+        CurrentVersion="1.1.0"
+        printf "\n CurrentVersion: %s" "$CurrentVersion"
+        printf "\n\n Checking for updates....   "
+        LatestVersion="$(floatversion -M "$(curl -sf --max-time 5 "https://github.com/TuxVinyards/floatversion/releases" | grep 's/tag')" 2>/dev/null)"
+        if [[ $LatestVersion ]]; then  
+          printf "LatestVersion: %s " "$LatestVersion"
+          if floatversion --gt "$LatestVersion $CurrentVersion" 2>/dev/null; then printf " UPGRADEABLE "
+          else printf " Up-to-Date "
+          fi
+        else printf "connection/data not available"
+        fi
+        printf "\n\n (c) Alex Genovese  https://github.com/TuxVinyards/floatversion \n\n"
+        return 0 ;;
       -c|--col)
         ShowAsCol=1 ; shift ;;
       -r|--rev)
@@ -360,9 +374,9 @@ float_version_from_string ()  {
 # COMPACT VERSION, suitable for embedding into other scripts, if preferred  (help and annotation removed)
 # # NB make sure that locale is set in the main script. See notes at start.
 
-float_version ()  {
+floatversion ()  {
   # floatversion --options  "quoted-input-string-or-text-file" 
-  # (c) Alex Genovese - version 1.0.0 (compact) - Usage/Help/Details @ https://github.com/TuxVinyards/floatversion
+  # (c) Alex Genovese - version 1.1.0 (compact) - Usage/Help/Details @ https://github.com/TuxVinyards/floatversion
   local ShowAsStr= ; local ShowAsCol= ; local ShowMax= ; local ShowRev= ; local ShowAll= ; local SortNum= ; local GrepFull= 
   local InputText= ; local Nums= ; local NumsCount= ; local FilterString= ; local StartString= ; local DeleteString= ; local GTcompare=
   local UseSortV= ; local NoSortVfallback= ; declare -a NumArrTemp ; declare -a NumArrSorted ; declare -a SelectArrTemp 
@@ -381,27 +395,27 @@ float_version ()  {
       -g|--gt)      GTcompare=1 ; shift ;;
       --sort-v)     UseSortV=1 ; shift ;;
       --no-svb)     NoSortVfallback=1 ; shift ;;
-      *)  if [[ "$1" == '-'* ]]; then printf "\n  ERROR:  '%s'  not recognised \n" "$1" >&2 ; return 1
-          elif [[ $InputText ]]; then printf "\n  ERROR:  QUOTED Input String or Text File Name should be given only once \n" >&2 ; return 1
+      *)  if [[ "$1" == '-'* ]]; then printf "\n  ERROR:  '%s'  not recognised \n\n" "$1" >&2 ; return 1
+          elif [[ $InputText ]]; then printf "\n  ERROR:  QUOTED Input String or Text File Name should be given only once \n\n" >&2 ; return 1
           else InputText="$1" ; shift ; fi ;;
     esac
   done
   [[ -e "$InputText" ]] && InputText="$(cat -A "$InputText")"
   InputText="$(tr -cd '[:print:]' <<< "$InputText" | tr ';' ' ' | tr '$' ' ' | tr ' ' '\n' | grep -sE '[[:print:]]')" 
-  [[ ! $InputText ]] && printf "\n  ERROR: no input found.  Is '-i' or '-g' the last parameter plus input the last quoted element? \n" >&2 && return 1
+  [[ ! $InputText ]] && printf "\n  ERROR: no input found.  Is '-i' or '-g' the last parameter plus input the last quoted element? \n\n" >&2 && return 1
   [[ $FilterString ]] && mapfile -t FilterArr <<< "$(tr ' ' '\n' <<< "$FilterString")"
   [[ $StartString ]] && mapfile -t StartArr <<< "$(tr ' ' '\n' <<< "$StartString")"
   [[ $DeleteString ]] && mapfile -t DeleteArr <<< "$(tr ' ' '\n' <<< "$DeleteString")" 
   if [[ $ShowMax ]]; then ShowAsStr= ; ShowAsCol= ; elif [[ $ShowAsCol ]]; then ShowAsStr= ; else ShowAsStr=1 ; fi
   if [[ $UseSortV ]] &&  ! sort --help | grep -sq -o 'version-sort' ; then 
-    if [[ $NoSortVfallback ]]; then  printf "\n  Sorry, 'sort -V' is not available, you need 'jq' to run this script. \n" >&2 ; else UseSortV= ; fi
+    if [[ $NoSortVfallback ]]; then  printf "\n  Sorry, 'sort -V' is not available, you need 'jq' to run this script. \n\n" >&2 ; else UseSortV= ; fi
   fi
-  if [[ ! $UseSortV ]] && [[ ! "$(command -v jq)" ]]; then printf "\n  Sorry, you need to install 'jq' to run this script. \n" >&2 ; fi
+  if [[ ! $UseSortV ]] && [[ ! "$(command -v jq)" ]]; then printf "\n  Sorry, you need to install 'jq' to run this script. \n\n" >&2 ; fi
   [[ $GTcompare ]] && GrepFull=1
   if [[ $GrepFull ]]; then Nums="$(grep -sEo '[0-9]+([.][0-9]+)+([.][0-9]+)?+([.][0-9]+)?+([.][0-9]+)?+([-][[:alnum:]]+)?+([.][[:digit:]]+)?' <<< "$InputText" )"
   else Nums="$(grep -sEo '[0-9]+([.][0-9]+)+([.][0-9]+)?+([.][0-9]+)?+([.][0-9]+)?' <<< "$InputText" )"; fi ;  printf -v Nums "%s\n" "$Nums"
   Nums="$(grep -s '[[:print:]]' <<< "$Nums")" ; NumsCount="$(grep -sc '[[:print:]]' <<< "$Nums")" 
-  if [[ $GTcompare ]] && [[ "$NumsCount" != 2 ]]; then printf "\n  ERROR:  two floating point or semantic version values should be supplied" >&2 ; return 1 ; fi
+  if [[ $GTcompare ]] && [[ "$NumsCount" != 2 ]]; then printf "\n  ERROR:  two floating point or semantic version values should be supplied \n\n" >&2 ; return 1 ; fi
   [[ ! $Nums ]] && return 1
   mapfile -t NumArrTemp  <<< "$(tr ' ' '\n' <<< "$Nums")"
   if [[ $ShowAll ]]; then mapfile -t  NumArrSorted <<< "$(printf "%s\n" "${NumArrTemp[@]}")"
@@ -453,8 +467,8 @@ float_version ()  {
 ##
 
 # script call, developer option
-if [[ $1 == "-C" ]] || [[ $1 == "--compact" ]]; then shift ; float_version "$@"
-elif [[ $CompactVersion ]]; then  float_version "$@"
+if [[ $1 == "-C" ]] || [[ $1 == "--compact" ]]; then shift ; floatversion "$@"
+elif [[ $CompactVersion ]]; then  floatversion "$@"
 else float_version_from_string "$@"
 fi
 
