bump HomeBird up a version

diff --git a/qqX.builtins/homebird/quickget b/qqX.builtins/homebird/quickget
--- a/qqX.builtins/homebird/quickget
+++ b/qqX.builtins/homebird/quickget
@@ -308,51 +308,6 @@ function csv_data() {
     wait
 }
 
-function create_config() {
-    local VM_PATH="${1}"
-    local INPUT="${2}"
-    OS="custom"
-    if ! mkdir "${VM_PATH}" 2>/dev/null; then
-        echo "ERROR! Could not create directory: ${VM_PATH}. Please verify that it does not already exist"
-        exit 1
-    fi
-    if [[ "${INPUT}" == "http://"* ]] || [[ "${INPUT}" == "https://"* ]]; then
-        INPUT="$(web_redirect "${INPUT}")"
-        if [[ "${INPUT}" == *".iso" ]] || [[ "${INPUT}" == *".img" ]]; then
-            web_get "${INPUT}" "${VM_PATH}"
-            INPUT="${VM_PATH}/${INPUT##*/}"
-        else
-            echo "ERROR! Only ISO,IMG and QCOW2 file types are supported for --create-config"
-            exit 1
-        fi
-    fi
-    if [[ "${INPUT}" == *".iso" ]]; then
-        echo "Moving image to VM dir" && mv "${INPUT}" "${VM_PATH}"
-        CUSTOM_IMAGE_TYPE="iso"
-    elif [[ "${INPUT}" == *".img" ]]; then
-        echo "Moving image to VM dir" && mv "${INPUT}" "${VM_PATH}"
-        CUSTOM_IMAGE_TYPE="img"
-    elif [[ "${INPUT}" == *".qcow2" ]]; then
-        echo "Moving image to VM dir" && mv "${INPUT}" "${VM_PATH}/disk.qcow2"
-        CUSTOM_IMAGE_TYPE="qcow2"
-    else
-        echo "ERROR! Only ISO,IMG and QCOW2 file types are supported for --create-config"
-        exit 1
-    fi
-    echo "Creating custom VM config for ${INPUT##*/}."
-    case "${INPUT,,}" in
-        *windows-server*) CUSTOM_OS="windows-server";;
-        *windows*) CUSTOM_OS="windows";;
-        *freebsd*) CUSTOM_OS="freebsd";;
-        *kolibrios*) CUSTOM_OS="kolibrios";;
-        *reactos*) CUSTOM_OS="reactos";;
-        *) CUSTOM_OS="linux";;
-    esac
-    echo "Selecting OS: ${CUSTOM_OS}. If this is incorrect, please modify the config file to include the correct OS."
-    echo
-    make_vm_config "${INPUT}"
-}
-
 function list_supported() {
     list_csv | cut -d ',' -f2,3,4 | tr ',' ' '
     exit 0
@@ -1036,12 +991,17 @@ function editions_solus() {
 
 function releases_sparkylinux() {
     #shellcheck disable=SC2046,SC2005
-    echo $(web_pipe "https://sparkylinux.org/download/stable/" | grep "ISO image" | cut -d'-' -f3 | sort -ru)
+    echo $(web_pipe "https://sparkylinux.org/download/stable/" |  grep -E -o "sparkylinux-.*\.iso\"" | cut -d'-' -f2 | sort -ru)
 }
 
 function editions_sparkylinux() {
     #shellcheck disable=SC2046,SC2005
-    echo $(web_pipe "https://sparkylinux.org/download/stable/" | grep "ISO image" | cut -d'-' -f5 | cut -d'.' -f 1 | sort -u)
+    if [ -z "${RELEASE}" ]; then
+        echo $(web_pipe "https://sparkylinux.org/download/stable/" | grep -E -o "sparkylinux-.*\.iso\"" | cut -d'-' -f4 | cut -d'.' -f1 | sort -u)
+    else
+        echo $(web_pipe "https://sparkylinux.org/download/stable/" | grep -E -o "sparkylinux-${RELEASE}-.*\.iso\"" | cut -d'-' -f4 | cut -d'.' -f1 | sort -u)
+    fi
+    
 }
 
 function releases_spirallinux() {
@@ -1253,6 +1213,7 @@ function web_get() {
         echo 
         exit  #rm -f "${DIR}/${FILE}" # qqX needs to take control here
     fi
+
 }
 
 # checks if a URL needs to be redirected and returns the final URL
@@ -2657,7 +2618,9 @@ function get_zorin() {
 }
 
 function unattended_windows() {
-    cat << 'EOF' > "${1}"
+    mkdir -p "${1}/unattended" 2>/dev/null
+
+    cat << 'EOF' > "${1}/unattended/autounattend.xml"
 <?xml version="1.0" encoding="utf-8"?>
 <unattend xmlns="urn:schemas-microsoft-com:unattend"
   xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State"
@@ -2939,6 +2902,15 @@ function unattended_windows() {
   </settings>
 </unattend>
 EOF
+
+
+echo "Downloading Spice drivers..."
+web_get https://www.spice-space.org/download/windows/spice-webdavd/spice-webdavd-x64-latest.msi "${VM_PATH}/unattended"
+web_get https://www.spice-space.org/download/windows/vdagent/vdagent-win-0.10.0/spice-vdagent-x64-0.10.0.msi "${VM_PATH}/unattended"
+web_get https://www.spice-space.org/download/windows/usbdk/UsbDk_1.0.22_x64.msi "${VM_PATH}/unattended"
+
+echo "Making unattended.iso"
+mkisofs -quiet -l -o "${VM_PATH}/unattended.iso" "${VM_PATH}/unattended/"
 }
 
 function handle_curl_error() {
@@ -3119,12 +3091,14 @@ function download_windows_workstation() {
     local session_id=""
     local iso_download_page_html=""
     local product_edition_id=""
+    local language_skuid_table_cmd=""
     local language_skuid_table_html=""
     local sku_id=""
+    local iso_download_link_cmd=""
     local iso_download_link_html=""
     local iso_download_link=""
 
-    echo "Downloading Windows ${RELEASE} (${I18N})"
+    echo; echo "Downloading Windows ${RELEASE} (${I18N})"; echo
     # This function is adapted from the Mido project:
     # https://github.com/ElliotKillick/Mido
     # Download newer consumer Windows versions from behind gated Microsoft API
@@ -3137,8 +3111,18 @@ function download_windows_workstation() {
         10) url="${url}ISO";;
     esac
 
+    # Make log for dev analysis
+    { echo; date; echo; echo "$url"; echo 
+    } >  "/tmp/qe_win_dl_log.txt"
+
+    { echo "I18N Lang: $I18N"; echo 
+    } >>  "/tmp/qe_win_dl_log.txt"
+
     local user_agent="Mozilla/5.0 (X11; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0"
     session_id="$(uuidgen)"
+
+    { echo "$user_agent"; echo; uuidparse "$session_id"; echo 
+    } >>  "/tmp/qe_win_dl_log.txt"
 
     # Get product edition ID for latest release of given Windows version
     # Product edition ID: This specifies both the Windows release (e.g. 22H2) and edition ("multi-edition" is default, either Home/Pro/Edu/etc., we select "Pro" in the answer files) in one number
@@ -3151,11 +3135,25 @@ function download_windows_workstation() {
         return $?
     }
 
+    # Copyright (C) 2024 GPL3 Alex Genovese 
+    # https://github.com/TuxVinyards/qqX
+    # Slow down the 'bot' behaviour, make it seem more human, so the anti-ddos routines don't block us:
+    local RndNum=
+    RndNum="$( (tr -cd '0-5' | head -c 1) < /dev/urandom )"
+    echo " - Taking a few human seconds to 'read' the download page ... " ; sleep "1$RndNum"
+    echo "   ... to hopefully stop the anti-ddos and anti-bot routines from blocking us"
+
+    { echo; date; echo "iso_download_page_html:"; echo; echo "$iso_download_page_html"; echo ; echo "End of Page"; echo
+    } >  "/tmp/qe_win_dl_page_html.txt"
+
     echo -n " - Getting Product edition ID: "
     # tr: Filter for only numerics to prevent HTTP parameter injection
     # head -c was recently added to POSIX: https://austingroupbugs.net/view.php?id=407
     product_edition_id="$(echo "$iso_download_page_html" | grep -Eo '<option value="[0-9]+">Windows' | cut -d '"' -f 2 | head -n 1 | tr -cd '0-9' | head -c 16)"
     echo "$product_edition_id"
+
+    { echo "product_edition_id"; echo; echo "$product_edition_id"; echo 
+    } >>  "/tmp/qe_win_dl_log.txt"
 
     echo " - Permit Session ID: $session_id"
     # Permit Session ID
@@ -3166,8 +3164,14 @@ function download_windows_workstation() {
         return $?
     }
 
+    RndNum="$( (tr -cd '0-6' | head -c 1) < /dev/urandom )"
+    echo " - A few human seconds here too ...." ; sleep "1$RndNum"
+
     # Extract everything after the last slash
     local url_segment_parameter="${url##*/}"
+
+    { echo "url_segment_parameter:"; echo; echo "$url_segment_parameter"; echo 
+    } >>  "/tmp/qe_win_dl_log.txt"
 
     echo -n " - Getting language SKU ID: "
     # Get language -> skuID association table
@@ -3179,29 +3183,61 @@ function download_windows_workstation() {
         return $?
     }
 
+    language_skuid_table_cmd="$(echo --silent --request POST --user-agent "$user_agent" --data "" --header "Accept:" --max-filesize 10K --fail --proto =https --tlsv1.2 --http1.1 -- "https://www.microsoft.com/en-US/api/controls/contentinclude/html?pageId=a8f8f489-4c7f-463a-9ca6-5cff94d8d041&host=www.microsoft.com&segments=software-download,$url_segment_parameter&query=&action=getskuinformationbyproductedition&sessionId=$session_id&productEditionId=$product_edition_id&sdVersion=2")" 
+
+    { echo; date; echo "language_skuid_table_html - FULL "; echo; echo "$language_skuid_table_html"; echo ; echo "End of Page"; echo
+    } >  "/tmp/qe_win_dl_lang_table full.txt"
+
     # Limit untrusted size for input validation
     language_skuid_table_html="$(echo "$language_skuid_table_html" | head -c 10240)"
 
+    { echo "language_skuid_table_cmd"; echo; echo "curl $language_skuid_table_cmd"; echo 
+    } >>  "/tmp/qe_win_dl_log.txt"
+
+    { echo "language_skuid_table_html"; echo; echo "$language_skuid_table_html"; echo 
+    } >>  "/tmp/qe_win_dl_log.txt"
+
     # tr: Filter for only alphanumerics or "-" to prevent HTTP parameter injection
-    sku_id="$(echo "$language_skuid_table_html" | grep "${I18N}" | sed 's/&quot;//g' | cut -d ',' -f 1  | cut -d ':' -f 2 | tr -cd '[:alnum:]-' | head -c 16)"
+    sku_id="$(echo "$language_skuid_table_html" | grep "${I18N}&" | sed 's/&quot;//g' | cut -d ',' -f 1  | cut -d ':' -f 2 | tr -cd '[:alnum:]-' | head -c 16)"
     echo "$sku_id"
 
+    RndNum="$( (tr -cd '0-4' | head -c 1) < /dev/urandom )"
+    echo " - And a few human seconds here .... " ; sleep "1$RndNum"
+
+    { echo "sku_id"; echo; echo "$sku_id"; echo 
+    } >>  "/tmp/qe_win_dl_log.txt"
+
     echo " - Getting ISO download link..."
+    
     # Get ISO download link
     # If any request is going to be blocked by Microsoft it's always this last one (the previous requests always seem to succeed)
     # --referer: Required by Microsoft servers to allow request
     iso_download_link_html="$(curl --silent --request POST --user-agent "$user_agent" --data "" --referer "$url" --header "Accept:" --max-filesize 100K --fail --proto =https --tlsv1.2 --http1.1 -- "https://www.microsoft.com/en-US/api/controls/contentinclude/html?pageId=6e2a1789-ef16-4f27-a296-74ef7ef5d96b&host=www.microsoft.com&segments=software-download,$url_segment_parameter&query=&action=GetProductDownloadLinksBySku&sessionId=$session_id&skuId=$sku_id&language=English&sdVersion=2")"
+    iso_download_link_cmd="$(echo --silent --request POST --user-agent "$user_agent" --data "" --referer "$url" --header "Accept:" --max-filesize 100K --fail --proto =https --tlsv1.2 --http1.1 -- "https://www.microsoft.com/en-US/api/controls/contentinclude/html?pageId=6e2a1789-ef16-4f27-a296-74ef7ef5d96b&host=www.microsoft.com&segments=software-download,${url_segment_parameter}&query=&action=GetProductDownloadLinksBySku&sessionId=${session_id}&skuId=${sku_id}&language=English&sdVersion=2")"
+
+    RndNum="$( (tr -cd '2-5' | head -c 1) < /dev/urandom )"
+    echo " - And some more, hopefully successful, human seconds before we start .... " ; sleep "1$RndNum"
+
+    { echo "iso_download_link_cmd"; echo; echo "curl $iso_download_link_cmd"; echo 
+    } >>  "/tmp/qe_win_dl_log.txt"
+
+    { echo "iso_download_link_html"; echo; echo "$iso_download_link_html"; echo 
+    } >>  "/tmp/qe_win_dl_log.txt"
 
     local failed=0
-
     if ! [ "$iso_download_link_html" ]; then
         # This should only happen if there's been some change to how this API works
-        echo " - Microsoft servers gave us an empty response to our request for an automated download."
+        echo; echo " - Microsoft servers gave us an empty response to our request for an automated download."
         failed=1
     fi
 
     if echo "$iso_download_link_html" | grep -q "We are unable to complete your request at this time."; then
-        echo " - WARNING! Microsoft blocked the automated download request based on your IP address."
+        echo; echo " - UNFORTUNATELY: Microsoft blocked the download request based on your IP address."; echo
+        failed=1
+    fi
+
+    if echo "$iso_download_link_html" | grep -q "We encountered a problem processing your request. Please try again later."; then
+        echo; echo " - UNFORTUNATELY: Microsoft blocked the request and is saying to try again later."; echo
         failed=1
     fi
 
@@ -3209,7 +3245,7 @@ function download_windows_workstation() {
         echo "   Manually download the Windows ${windows_version} ISO using a web browser from: ${url}"
         echo "   Save the downloaded ISO to: $(realpath "${VM_PATH}")"
         echo "   Update the config file to reference the downloaded ISO: ./${VM_PATH}.conf"
-        echo "   Continuing with the VM creation process..."
+        echo "   Continuing with the VM creation process..." ; echo
         return 1
     fi
 
@@ -3217,10 +3253,13 @@ function download_windows_workstation() {
     # sed: HTML decode "&" character
     # tr: Filter for only alphanumerics or punctuation
     iso_download_link="$(echo "$iso_download_link_html" | grep -o "https://software.download.prss.microsoft.com.*IsoX64" | cut -d '"' -f 1 | sed 's/&amp;/\&/g' | tr -cd '[:alnum:][:punct:]')"
+    
+    { echo "iso_download_link - filtered"; echo; echo "$iso_download_link"; echo 
+    } >>  "/tmp/qe_win_dl_log.txt"
 
     if ! [ "$iso_download_link" ]; then
         # This should only happen if there's been some change to the download endpoint web address
-        echo " - Microsoft servers gave us no download link to our request for an automated download. Please manually download this ISO in a web browser: $url"
+        echo " - Microsoft servers gave us no download link to our request for an automated download."; echo "   Please manually download this ISO in a web browser:"; echo "   $url"
         return 1
     fi
 
@@ -3229,6 +3268,10 @@ function download_windows_workstation() {
     # Download ISO
     FILE_NAME="$(echo "$iso_download_link" | cut -d'?' -f1 | cut -d'/' -f5)"
     web_get "${iso_download_link}" "${VM_PATH}" "${FILE_NAME}"
+
+    { echo "FILE_NAME"; echo; echo "$FILE_NAME"; echo 
+    } >>  "/tmp/qe_win_dl_log.txt"
+    
 }
 
 function get_windows() {
@@ -3248,13 +3291,7 @@ function get_windows() {
     rm -f "${VM_PATH}/unattended.iso"
     case ${RELEASE} in
         10|11)
-            mkdir -p "${VM_PATH}/unattended" 2>/dev/null
-            web_get https://www.spice-space.org/download/windows/spice-webdavd/spice-webdavd-x64-latest.msi "${VM_PATH}/unattended"
-            web_get https://www.spice-space.org/download/windows/vdagent/vdagent-win-0.10.0/spice-vdagent-x64-0.10.0.msi "${VM_PATH}/unattended"
-            web_get https://www.spice-space.org/download/windows/usbdk/UsbDk_1.0.22_x64.msi "${VM_PATH}/unattended"
-            echo "Making unattended.iso"
-            unattended_windows "${VM_PATH}/unattended/autounattend.xml"
-            mkisofs -quiet -l -o "${VM_PATH}/unattended.iso" "${VM_PATH}/unattended/"
+            unattended_windows "${VM_PATH}"
             ;;
     esac
 
@@ -3326,12 +3363,76 @@ function create_vm() {
     make_vm_config "${ISO}"
 }
 
+function create_config() {
+    local VM_PATH="${1}"
+    local INPUT="${2}"
+    local FIXED_ISO=""
+
+    OS="custom"
+    if ! mkdir "${VM_PATH}" 2>/dev/null; then
+        echo "ERROR! Could not create directory: ${VM_PATH}. Please verify that it does not already exist"
+        exit 1
+    fi
+    if [[ "${INPUT}" == "http://"* ]] || [[ "${INPUT}" == "https://"* ]]; then
+        INPUT="$(web_redirect "${INPUT}")"
+        if [[ "${INPUT}" == *".iso" ]] || [[ "${INPUT}" == *".img" ]]; then
+            web_get "${INPUT}" "${VM_PATH}"
+            INPUT="${INPUT##*/}"
+        else
+            echo "ERROR! Only ISO,IMG and QCOW2 file types are supported for --create-config"
+            exit 1
+        fi
+    fi
+
+    if [ ! -f "${INPUT}" ]; then
+        echo "ERROR! The input must be a valid URL or path to an ISO, IMG, or QCOW2 file."
+        exit 1
+    elif [[ "${INPUT}" == *".iso" ]]; then
+        echo "Moving image to VM dir" && mv "${INPUT}" "${VM_PATH}"
+        CUSTOM_IMAGE_TYPE="iso"
+    elif [[ "${INPUT}" == *".img" ]]; then
+        echo "Moving image to VM dir" && mv "${INPUT}" "${VM_PATH}"
+        CUSTOM_IMAGE_TYPE="img"
+    elif [[ "${INPUT}" == *".qcow2" ]]; then
+        echo "Moving image to VM dir" && mv "${INPUT}" "${VM_PATH}/disk.qcow2"
+        CUSTOM_IMAGE_TYPE="qcow2"
+    else
+        echo "ERROR! Only ISO,IMG and QCOW2 file types are supported for --create-config"
+        exit 1
+    fi
+    INPUT="$(basename "${INPUT}")"
+
+    echo "Creating custom VM config for ${INPUT##*/}."
+    case "${INPUT,,}" in
+        *freebsd*) CUSTOM_OS="freebsd";;
+        *kolibrios*) CUSTOM_OS="kolibrios";;
+        *reactos*) CUSTOM_OS="reactos";;
+        *windows-server*|*eval_oemret_x*|*eval_x*) CUSTOM_OS="windows-server";;
+        *windows*|win*)
+            CUSTOM_OS="windows"
+            # Older windows 10 ISOs use the year followed by the month rather than the year & half). Match any text for language.
+            if [ "${3}" != "--disable-unattended" ] && ( [ "${3}" == "--unattended" ] || grep -E -q 'Win(10|11)_([0-9]{2}H(1|2)|[0-9]{4})_[^.]*?(x64|x32)(v[0-9])?.iso' <<< "${INPUT}" ); then
+                echo "Creating unattended Windows installation files. To disable, pass --disable-unattended"
+                echo
+                echo "Downloading VirtIO drivers..."
+                web_get "https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso" "${VM_PATH}"
+                FIXED_ISO="virtio-win.iso"
+                rm -f "${VM_PATH}/unattended.iso"
+                unattended_windows "${VM_PATH}"
+            fi
+            ;;
+
+        *) CUSTOM_OS="linux";;
+    esac
+    echo -e "Selecting OS: ${CUSTOM_OS}. If this is incorrect, please modify the config file to include the correct OS.\n"
+    make_vm_config "${INPUT}" "${FIXED_ISO}"
+}
+
 # Use type -p command to check if quickemu is in the system's PATH and
 # fallback to checking if quickemu is in the current directory.
-function resolve_quickemu() {
-    if type -p quickemu >/dev/null 2>&1; then
-        type -p quickemu
-    elif [ -f "./quickemu" ]; then
+function resolve_quickemu() {   
+    type -p quickemu || \
+    if [ -x "./quickemu" ]; then
         echo "$(pwd)/quickemu"
     else
         echo "quickemu not found" >&2
@@ -3363,11 +3464,14 @@ Advanced usage:
 
 Arguments:
   --download      <os> <release> [edition] : Download image; no VM configuration
-  --create-config <os> [path/url]          : Create VM config for a OS image
+  --create-config <os> [path/url] [flags]  : Create VM config for a OS image
   --open-homepage <os>                     : Open homepage for the OS
   --show          [os]                     : Show OS information
   --version                                : Show version
   --help                                   : Show this help message
+------------------------------------ Flags -------------------------------------
+--create-config:
+  --disable-unattended                     : Force quickget not to set up an unattended installation
 -------------------------- For testing & development ---------------------------
   --url           [os] [release] [edition] : Show image URL(s)
   --check         [os] [release] [edition] : Check image URL(s)
@@ -3431,7 +3535,7 @@ case "${1}" in
     --version|-version)
         #WHERE=$(dirname "${BASH_SOURCE[0]}")
         #"${WHERE}/quickemu" --version
-        echo "HB 4.9.6.01"
+        echo "HB 4.9.6.04"
         exit 0;;
     --help|-help|--h|-h)
         help_message
@@ -3494,7 +3598,7 @@ if [ -n "${2}" ]; then
             fi
         else
             show_os_info "${OS}"
-            echo -e " - Editions:\t$("editions_${OS} | fmt -w 80")"
+            echo -e " - Editions:\t$("editions_${OS}" | fmt -w 80)"
             echo -e "\nERROR! You must specify an edition."
             exit 1
         fi
