add subtractive MacOS  dev options
on tests, both haswell & skylake -ve  perform well
but skylake3 seems to manage IBRS (spectre-mitigation)
and is still faster than Haswell +ve i=on timed tests
use cpu_cores="8" in .conf

diff --git a/qqX.builtins/freebird/quickemu b/qqX.builtins/freebird/quickemu
--- a/qqX.builtins/freebird/quickemu
+++ b/qqX.builtins/freebird/quickemu
@@ -537,53 +537,91 @@ function vm_boot() {
         # as is only officially supported Sonoma CPU and supports more cores: 16, 20 
         # See https://en.wikipedia.org/wiki/IMac_Pro#Technical_specifications 
         # Edit .conf file to cpu_cores="16"  ie 8 core x 2 threads
- 
+
         CPU_MODEL="Haswell-v2"
         #CPU_MODEL="Skylake-Server-v3"
-        CPU="-cpu ${CPU_MODEL},kvm=on,vendor=GenuineIntel,-pdpe1gb,+avx,+sse,+sse2,+ssse3,vmware-cpuid-freq=on"
-        # A CPU with fma is required for Metal support (@flexiondotorg)
 
-        case ${macos_release} in
-            ventura|sonoma)
-                # A CPU with AVX2 support is required for >= macOS Ventura
-                if check_cpu_flag sse4_2 && check_cpu_flag avx2; then 
-                    CPU+=",+avx2,+sse4.1,+sse4.2"
-                else
-                    echo "ERROR! macOS ${macos_release} requires a CPU with SSE 4.2 and AVX2 support."
-                    echo "       Try macOS Monterey or Big Sur."
-                    exit 1
-                fi ;;
-            catalina|big-sur|monterey)
-                # A CPU with SSE4.2 support is required for >= macOS Catalina
-                if check_cpu_flag sse4_2; then
-                    CPU+=",+sse4.1,+sse4.2"
-                else
-                    echo "ERROR! macOS ${macos_release} requires a CPU with SSE 4.2 support."
-                    exit 1
-                fi ;;
-            *)
-                # A CPU with SSE4.1 support is required for >= macOS Sierra
-                if check_cpu_flag sse4_1; then
-                     CPU+=",+sse4.1"
-                else
-                    echo "ERROR! macOS ${macos_release} requires a CPU with SSE 4.1 support."
-                    exit 1
-                fi ;;
-        esac
+        # A CPU with fma is required for Mac Graphics 'Metal' support (@flexiondotorg)
 
-        for FLAG in abm aes apic arat bmi1 bmi2 clflush cmov cx8 cx16 de \
-                    erms f16c fma fp87 fsgsbase fxsr invpcid invtsc lahf_lm lm \
-                    mca mce mmx movbe mpx msr mtrr nx pae pat pcid pge pse popcnt pse36 \
-                    rdrand rdtscp sep smep syscall tsc tsc_adjust vaes vbmi2 vmx vpclmulqdq \
-                    x2apic xgetbv1 xsave xsaveopt; do
-                if check_cpu_flag "$FLAG"; then
-                    QEMU_CPU_FLAG="${FLAG//_/-}"
-                    CPU+=",+${QEMU_CPU_FLAG}"
-                fi
-        done
+        # Dev Subtractive method: Set =1 or blank  Allow Qemu to add all, unless not present in host.
+        # Use "sysctl -a | grep machdep.cpu" at terminal in MacOS to see flags
+
+        UseSubtractiveCPU=
+
+        if [[ $UseSubtractiveCPU ]]; then
+
+            CPU="-cpu ${CPU_MODEL},kvm=on,vendor=GenuineIntel,vmware-cpuid-freq=on"
+
+            case ${macos_release} in
+                ventura|sonoma)
+                    # A CPU with AVX2 support is required for >= macOS Ventura
+                    if ! check_cpu_flag sse4_2 && check_cpu_flag avx2; then 
+                        echo "ERROR! macOS ${macos_release} requires a CPU with SSE 4.2 and AVX2 support."
+                        echo "       Try macOS Monterey or Big Sur."
+                        exit 1
+                    fi ;;
+                catalina|big-sur|monterey)
+                    # A CPU with SSE4.2 support is required for >= macOS Catalina
+                    if ! check_cpu_flag sse4_2; then
+                        echo "ERROR! macOS ${macos_release} requires a CPU with SSE 4.2 support."
+                        exit 1
+                    fi ;;
+                *)
+                    # A CPU with SSE4.1 support is required for >= macOS Sierra
+                    if ! check_cpu_flag sse4_1; then
+                        echo "ERROR! macOS ${macos_release} requires a CPU with SSE 4.1 support."
+                        exit 1
+                    fi ;;
+            esac
+
+        else
+
+            CPU="-cpu ${CPU_MODEL},kvm=on,vendor=GenuineIntel,-pdpe1gb,+avx,+sse,+sse2,+ssse3,vmware-cpuid-freq=on"
+            # A CPU with fma is required for Metal support (@flexiondotorg)
+
+            case ${macos_release} in
+                ventura|sonoma)
+                    # A CPU with AVX2 support is required for >= macOS Ventura
+                    if check_cpu_flag sse4_2 && check_cpu_flag avx2; then 
+                        CPU+=",+avx2,+sse4.1,+sse4.2"
+                    else
+                        echo "ERROR! macOS ${macos_release} requires a CPU with SSE 4.2 and AVX2 support."
+                        echo "       Try macOS Monterey or Big Sur."
+                        exit 1
+                    fi ;;
+                catalina|big-sur|monterey)
+                    # A CPU with SSE4.2 support is required for >= macOS Catalina
+                    if check_cpu_flag sse4_2; then
+                        CPU+=",+sse4.1,+sse4.2"
+                    else
+                        echo "ERROR! macOS ${macos_release} requires a CPU with SSE 4.2 support."
+                        exit 1
+                    fi ;;
+                *)
+                    # A CPU with SSE4.1 support is required for >= macOS Sierra
+                    if check_cpu_flag sse4_1; then
+                        CPU+=",+sse4.1"
+                    else
+                        echo "ERROR! macOS ${macos_release} requires a CPU with SSE 4.1 support."
+                        exit 1
+                    fi ;;
+            esac
+
+            for FLAG in abm aes apic arat bmi1 bmi2 clflush cmov cx8 cx16 de \
+                        erms f16c fma fp87 fsgsbase fxsr invpcid invtsc lahf_lm lm \
+                        mca mce mmx movbe mpx msr mtrr nx pae pat pcid pge pse popcnt pse36 \
+                        rdrand rdtscp sep smep syscall tsc tsc_adjust vaes vbmi2 vmx vpclmulqdq \
+                        x2apic xgetbv1 xsave xsaveopt; do
+                    if check_cpu_flag "$FLAG"; then
+                        QEMU_CPU_FLAG="${FLAG//_/-}"
+                        CPU+=",+${QEMU_CPU_FLAG}"
+                    fi
+            done
+
+        fi
 
         if [[ $CPU_MODEL == "Skylake-Server-v3" ]]; then
-            for FLAG in clwb adx smap ; do
+            for FLAG in clwb adx smap pdpe1gb; do
                     if ! check_cpu_flag "$FLAG"; then
                         QEMU_CPU_FLAG="${FLAG//_/-}"
                         CPU+=",-${QEMU_CPU_FLAG}"
