add freespirit testing msg  and further notes

diff --git a/qqX.builtins/freespirit/quickget b/qqX.builtins/freespirit/quickget
--- a/qqX.builtins/freespirit/quickget
+++ b/qqX.builtins/freespirit/quickget
@@ -14,13 +14,19 @@ if [[ -e "$(pwd)/qqX_quickget_mods" ]]; then
         OriginalPATH="$PATH"
         CurrentFolder="$(pwd)"
         if [[ -e "/usr/share/qqX/qqX.lib/fv" ]]; then qqX_LibraryFolder="/usr/share/qqX/qqX.lib"
-        else printf "\n\n  qqX libraries not found OR qqX running elsewhere ... \n\n" ; exit 1
+        else printf "\n\n  qqX libraries not found .... \n\n" ; exit 1
         fi
         export PATH="$CurrentFolder:${qqX_LibraryFolder}:${OriginalPATH}"
         if  grep -sqi 'C.utf8' <<< "$(locale -a)"; then export "LC_NUMERIC=C.UTF-8" ; export "LC_COLLATE=C.UTF-8"
         else export "LC_NUMERIC=C" ; export "LC_COLLATE=C"
         fi
     fi
+elif [[ "$PATH" != *'qqX'* ]]; then
+    printf "\n  This individual code branch is intended to be run as a qqX built-in."
+    printf "\n\n  qqX mod files and libraries have not been found ... ?"
+    printf "\n\n  If running from a cloned Quickemu fork, you need to switch branches"
+    printf "\n  or need to download qqX and run from a terminal opened in the FreeSpirit folder. \n\n"
+    exit 1
 fi
 
 function cleanup() {
