add freebird/spirit updates  tweak wget --spider

diff --git a/qqX.builtins/freespirit/quickemu b/qqX.builtins/freespirit/quickemu
--- a/qqX.builtins/freespirit/quickemu
+++ b/qqX.builtins/freespirit/quickemu
@@ -250,12 +250,14 @@ function vm_boot() {
     elif [ -e /etc/os-release ]; then
         LSB_DESCRIPTION=$(grep PRETTY_NAME /etc/os-release | cut -d'"' -f2)
     fi
+    # Strip quotes from LSB_DESCRIPTION
+    LSB_DESCRIPTION="$(echo "${LSB_DESCRIPTION}" | sed 's/"//g')"
 
     echo "Quickemu ${VERSION} using ${QEMU} v${QEMU_VER_LONG}"
     echo " - Host:     ${LSB_DESCRIPTION} running ${KERNEL_NAME} ${KERNEL_VER} ${KERNEL_NODE}"
 
     HOST_CPU_CORES=$(nproc)
-    HOST_CPU_MODEL=$(lscpu | grep '^Model name:' | cut -d':' -f2 | sed 's/  //g')
+    HOST_CPU_MODEL=$(lscpu | grep '^Model name:' | cut -d':' -f2 | sed -e 's/^[[:space:]]*//')
     HOST_CPU_SOCKETS=$(lscpu | grep -E 'Socket' | cut -d':' -f2 | sed 's/ //g')
     HOST_CPU_VENDOR=$(lscpu | grep -E 'Vendor' | cut -d':' -f2 | sed 's/ //g')
 
@@ -288,6 +290,12 @@ function vm_boot() {
         GUEST_CPU_CORES="${cpu_cores}"
     fi
 
+    if [ "${guest_os}" == "macos" ] && [ "${GUEST_CPU_CORES}" -gt 10 ] || [ "${GUEST_CPU_CORES}" -eq 6 ] || [ "${GUEST_CPU_CORES}" -eq 7 ]; then
+        # macOS guests cannot boot with most core counts not powers of 2. This will fix the issue by rounding the core count down to a power of 2. Uses wc and factor from coreutils.
+        factorCPUCores=$(factor "${GUEST_CPU_CORES}")
+        GUEST_CPU_CORES=$(( 2 ** $(echo "${factorCPUCores#*:}" | grep -o '[0-9]' | wc -l) ))
+    fi
+
     # Account for Hyperthreading/SMT.
     if [ -e /sys/devices/system/cpu/smt/control ] && [ "${GUEST_CPU_CORES}" -ge 2 ]; then
         HOST_CPU_SMT=$(cat /sys/devices/system/cpu/smt/control)
@@ -313,9 +321,8 @@ function vm_boot() {
     local RAM_VM="2G"
     if [ -z "${ram}" ]; then
         local RAM_HOST=""
-        RAM_HOST=$(free --mega -h | grep Mem | cut -d':' -f2 | cut -d'G' -f1 | sed 's/ //g')
-        #Round up - https://github.com/wimpysworld/quickemu/issues/11
-        RAM_HOST=$(printf '%.*f\n' 0 "${RAM_HOST}")
+        # Determine the number of gigabytes of RAM in the host by extracting the first numerical value from the output.
+        RAM_HOST=$(free --giga | tr ' ' '\n' | grep -m 1 [0-9])
         if [ "${RAM_HOST}" -ge 128 ]; then
             RAM_VM="32G"
         elif [ "${RAM_HOST}" -ge 64 ]; then
@@ -330,7 +337,7 @@ function vm_boot() {
     fi
     echo ", ${RAM_VM} RAM"
 
-    if [ "${guest_os}" == "macos" ] || [ "${guest_os}" == "windows" ]; then
+    if [ "${guest_os}" == "macos" ] || [ "${guest_os}" == "windows" ] || [ "${guest_os}" == "windows-server" ]; then
         if [ "${RAM_VM//G/}" -lt 4 ]; then
             echo "ERROR! You have insufficient RAM to run ${guest_os} in a VM"
             exit 1
@@ -341,7 +348,7 @@ function vm_boot() {
     boot=${boot,,}
     guest_os=${guest_os,,}
 
-    if [ "${guest_os}" == "macos" ] || [ "${guest_os}" == "windows" ]; then
+    if [ "${guest_os}" == "macos" ] || [ "${guest_os}" == "windows" ] || [ "${guest_os}" == "windows-server" ]; then
         # Display MSRs alert if the guest is macOS or windows
         ignore_msrs_alert
     fi
@@ -472,7 +479,7 @@ function vm_boot() {
 
     # Make any OS specific adjustments
     case ${guest_os} in
-    batocera|*bsd|freedos|haiku|linux|*solaris)
+    batocera|*bsd|freedos|haiku|linux*|*solaris)
         CPU="-cpu host,kvm=on"
         if [ "${HOST_CPU_VENDOR}" == "AuthenticAMD" ]; then
             CPU="${CPU},topoext"
@@ -520,9 +527,9 @@ function vm_boot() {
         # A CPU with SSE4.1 support is required for >= macOS Sierra
         # A CPU with AVX2 support is required for >= macOS Ventura
         case ${macos_release} in
-        ventura)
+        ventura|sonoma)
             if check_cpu_flag sse4_1 && check_cpu_flag avx2; then
-                CPU="-cpu Haswell,kvm=on,vendor=GenuineIntel,+sse3,+sse4.2,+aes,+xsave,+avx,+xsaveopt,+xsavec,+xgetbv1,+avx2,+bmi2,+smep,+bmi1,+fma,+movbe,+invtsc,+avx2"
+                CPU="-cpu Broadwell-noTSX-IBRS,kvm=on,vendor=GenuineIntel,+sse,+sse4.1,+avx,+avx2,+hypervisor,+popcnt,+aes,+xsave,+xsavec,+xsaveopt,+xgetbv1,+bmi1,+bmi2,+smep,+fma,+movbe,+invtsc"
             else
                 echo "ERROR! macOS ${macos_release} requires a CPU with SSE 4.1 and AVX2 support."
                 exit 1
@@ -542,7 +549,14 @@ function vm_boot() {
 
         OSK=$(echo "bheuneqjbexolgurfrjbeqfthneqrqcyrnfrqbagfgrny(p)NccyrPbzchgreVap" | tr 'A-Za-z' 'N-ZA-Mn-za-m')
         # Disable S3 support in the VM to prevent macOS suspending during install
-        GUEST_TWEAKS="-no-hpet -global kvm-pit.lost_tick_policy=discard -global ICH9-LPC.disable_s3=1 -device isa-applesmc,osk=${OSK}"
+        GUEST_TWEAKS="-global kvm-pit.lost_tick_policy=discard -global ICH9-LPC.disable_s3=1 -device isa-applesmc,osk=${OSK}"
+
+        # Disable High Precision Timer
+        if [ "${QEMU_VER_SHORT}" -ge 70 ]; then
+          MACHINE_TYPE+=",hpet=off"
+        else
+          GUEST_TWEAKS+=" -no-hpet"
+        fi
 
         # Tune Qemu optimisations based on the macOS release, or fallback to lowest
         # common supported options if none is specified.
@@ -557,12 +571,13 @@ function vm_boot() {
             NET_DEVICE="vmxnet3"
             USB_HOST_PASSTHROUGH_CONTROLLER="usb-ehci"
             ;;
-        big-sur|monterey|ventura)
+        big-sur|monterey|ventura|sonoma)
             BALLOON="-device virtio-balloon"
             MAC_DISK_DEV="virtio-blk-pci"
             NET_DEVICE="virtio-net"
             USB_HOST_PASSTHROUGH_CONTROLLER="nec-usb-xhci"
             GUEST_TWEAKS="${GUEST_TWEAKS} -global nec-usb-xhci.msi=off"
+            USB_CONTROLLER="xhci"
             ;;
         *)
             # Backwards compatibility if no macos_release is specified.
@@ -578,7 +593,7 @@ function vm_boot() {
             disk_size="96G"
         fi
         ;;
-    windows)
+    windows|windows-server)
         if [ "${QEMU_VER_SHORT}" -gt 60 ]; then
             CPU="-cpu host,kvm=on,+hypervisor,+invtsc,l3-cache=on,migratable=no,hv_passthrough"
         else
@@ -589,7 +604,14 @@ function vm_boot() {
         fi
         # Disable S3 support in the VM to ensure Windows can boot with SecureBoot enabled
         #  - https://wiki.archlinux.org/title/QEMU#VM_does_not_boot_when_using_a_Secure_Boot_enabled_OVMF
-        GUEST_TWEAKS="-no-hpet -global kvm-pit.lost_tick_policy=discard -global ICH9-LPC.disable_s3=1"
+        GUEST_TWEAKS="-global kvm-pit.lost_tick_policy=discard -global ICH9-LPC.disable_s3=1"
+
+        # Disable High Precision Timer
+        if [ "${QEMU_VER_SHORT}" -ge 70 ]; then
+          MACHINE_TYPE+=",hpet=off"
+        else
+          GUEST_TWEAKS+=" -no-hpet"
+        fi
 
         if [ -z "${disk_size}" ]; then
             disk_size="64G"
@@ -720,7 +742,9 @@ function vm_boot() {
     fi
 
     # https://www.kraxel.org/blog/2019/09/display-devices-in-qemu/
-    if [ "${guest_os}" == "linux" ]; then
+    if [ "${guest_os}" == "linux_old" ]; then
+        DISPLAY_DEVICE="vmware-svga"
+    elif [ "${guest_os}" == "linux" ]; then
         case ${OUTPUT} in
         none|spice|spice-app)
             DISPLAY_DEVICE="virtio-gpu";;
@@ -731,7 +755,7 @@ function vm_boot() {
         # qxl-vga supports seamless mouse and sane resolutions if only one scanout
         # is used. Which is whay '-vga none' is added to the QEMU command line.
         DISPLAY_DEVICE="qxl-vga"
-    elif [ "${guest_os}" == "windows" ]; then
+    elif [ "${guest_os}" == "windows" ] || [ "${guest_os}" == "windows-server" ]; then
         case ${OUTPUT} in
         # virtio-gpu "works" with gtk but is limited to 1024x1024 and exhibits other issues.
         # https://kevinlocke.name/bits/2021/12/10/windows-11-guest-virtio-libvirt/#video
@@ -770,7 +794,11 @@ function vm_boot() {
 
     # Try and coerce the display resolution for Linux guests only.
     if [ "${guest_os}" == "linux" ]; then
-        VIDEO="${VIDEO},xres=${X_RES},yres=${Y_RES}"
+        if [ -n "${WIDTH}" ] && [ -n "${HEIGHT}" ]; then
+            VIDEO="${VIDEO},xres=${WIDTH},yres=${HEIGHT}"
+        else
+            VIDEO="${VIDEO},xres=${X_RES},yres=${Y_RES}"
+        fi
     fi
 
     # Allocate VRAM to VGA devices
@@ -896,7 +924,7 @@ function vm_boot() {
         esac
     fi
 
-    if [ "${guest_os}" != "windows" ] && [ -n "${PUBLIC}" ]; then
+    if [ "${guest_os}" != "windows" ] || [ "${guest_os}" == "windows-server" ] && [ -n "${PUBLIC}" ]; then
         echo -n " - 9P:       On guest: "
         if [ "${guest_os}" == "linux" ]; then
             echo "sudo mount -t 9p -o trans=virtio,version=9p2000.L,msize=104857600 ${PUBLIC_TAG} ~/$(basename "${PUBLIC}")"
@@ -972,9 +1000,14 @@ function vm_boot() {
         -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3
         -device pci-ohci,id=smartpass
         -device usb-ccid
-        -chardev spicevmc,id=ccid,name=smartcard
-        -device ccid-card-passthru,chardev=ccid
     )
+
+    if "${QEMU}" -chardev spicevmc,id=ccid,name= 2>&1 | grep -q smartcard; then
+        args+=(-chardev spicevmc,id=ccid,name=smartcard
+               -device ccid-card-passthru,chardev=ccid)
+    else
+        echo "WARNING! ${QEMU} was not compiled with support for smartcard devices"
+    fi
 
     # setup usb-controller
     [ -z "${USB_CONTROLLER}" ] && USB_CONTROLLER="$usb_controller"
@@ -1142,15 +1175,19 @@ function vm_boot() {
         # shellcheck disable=SC2054,SC2206
         args+=(-drive if=ide,index=0,media=disk,file="${disk_img}")
 
+    elif [ "${guest_os}" == "windows-server" ]; then
+        args+=(-device ide-hd,drive=SystemDisk
+            -drive id=SystemDisk,if=none,format=qcow2,file="${disk_img}" ${STATUS_QUO})
+
     else
         # shellcheck disable=SC2054,SC2206
         args+=(-device virtio-blk-pci,drive=SystemDisk
-            -drive id=SystemDisk,if=none,format=qcow2,file="${disk_img}" ${STATUS_QUO})
+            -drive id=SystemDisk,if=none,format=${disk_format:-qcow2},file="${disk_img}" ${STATUS_QUO})
     fi
 
     # https://wiki.qemu.org/Documentation/9psetup
     # https://askubuntu.com/questions/772784/9p-libvirt-qemu-share-modes
-    if [ "${guest_os}" != "windows" ] && [ -n "${PUBLIC}" ]; then
+    if [ "${guest_os}" != "windows" ] || [ "${guest_os}" == "windows-server" ] && [ -n "${PUBLIC}" ]; then
         # shellcheck disable=SC2054
         args+=(-fsdev local,id=fsdev0,path="${PUBLIC}",security_model=mapped-xattr
             -device virtio-9p-pci,fsdev=fsdev0,mount_tag="${PUBLIC_TAG}")
@@ -1335,9 +1372,9 @@ EOF
 function usage() {
     echo
     echo "Usage"
-    echo "  ${LAUNCHER} --vm ubuntu.conf"
+    echo "  ${LAUNCHER} --vm ubuntu.conf [optional params]"
     echo
-    echo "You can also pass optional parameters"
+    echo "List of optional parameters:"
     echo "  --access                          : Enable remote spice access support. 'local' (default), 'remote', 'clientipaddress'"
     echo "  --braille                         : Enable braille support. Requires SDL."
     echo "  --delete-disk                     : Delete the disk image and EFI variables"
@@ -1354,6 +1391,8 @@ function usage() {
     echo "  --snapshot info                   : Show disk/snapshot info."
     echo "  --status-quo                      : Do not commit any changes to disk/snapshot."
     echo "  --viewer <viewer>                 : Choose an alternative viewer. @Options: 'spicy' (default), 'remote-viewer', 'none'"
+    echo "  --width <width>                   : Set VM screen width. Does nothing without --height"
+    echo "  --height <height>                 : Set VM screen height. Does nothing without --width"
     echo "  --ssh-port <port>                 : Set ssh-port manually"
     echo "  --spice-port <port>               : Set spice-port manually"
     echo "  --public-dir <path>               : Expose share directory. @Options: '' (default: xdg-user-dir PUBLICSHARE), '<directory>', 'none'"
@@ -1473,6 +1512,7 @@ function monitor_send_cmd {
 boot="efi"
 cpu_cores=""
 disk_img=""
+disk_format=""
 disk_size=""
 display=""
 extra_args=""
@@ -1491,6 +1531,8 @@ secureboot="off"
 tpm="off"
 usb_devices=()
 viewer="spicy"
+width=""
+height=""
 ssh_port=""
 spice_port=""
 public_dir=""
@@ -1533,6 +1575,8 @@ VMDIR=""
 VMNAME=""
 VMPATH=""
 VIEWER=""
+WIDTH=""
+HEIGHT=""
 SSH_PORT=""
 SPICE_PORT=""
 MONITOR=""
@@ -1554,7 +1598,8 @@ SOUND_CARD=""
 # shellcheck disable=SC2155
 readonly LAUNCHER=$(basename "${0}")
 readonly DISK_MIN_SIZE=$((197632 * 8))
-readonly VERSION="FS.4.9.2"
+readonly VERSION="FS.4.9.3 +"
+
 
 # TODO: Make this run the native architecture binary
 QEMU=$(command -v qemu-system-x86_64)
@@ -1651,6 +1696,14 @@ else
             VIEWER="${2}"
             shift
             shift;;
+        -width|--width)
+            WIDTH="${2}"
+            shift;
+            shift;;
+        -height|--height)
+            HEIGHT="${2}"
+            shift;
+            shift;;
         -ssh-port|--ssh-port)
             SSH_PORT="${2}"
             shift;
@@ -1695,6 +1748,10 @@ else
             KEYBOARD="${2}"
             shift;
             shift;;
+        -keyboard_layout|--keyboard_layout)
+            KEYBOARD_LAYOUT="${2}"
+            shift;
+            shift;;
         -mouse|--mouse)
             MOUSE="${2}"
             shift;
@@ -1731,11 +1788,23 @@ if [ -n "${VM}" ] && [ -e "${VM}" ]; then
         exit 1
     fi
 
+    if [ -e "${disk_img}" ]; then
+		DiskChkMsg="$("$QEMU_IMG" check -q "${disk_img}" 2>&1)"
+		if [[ $DiskChkMsg ]]; then
+		    echo; echo "ERROR! disk.qcow2 has problems. Try qemu-img check --help."
+		    echo; echo "$DiskChkMsg" ; echo
+		    exit 1
+		fi
+	fi
+
     VMDIR=$(dirname "${disk_img}")
     VMNAME=$(basename "${VM}" .conf)
     VMPATH=$(realpath "$(dirname "${VM}")")
     VM_MONITOR_SOCKETPATH="${VMDIR}/${VMNAME}-monitor.socket"
     VM_SERIAL_SOCKETPATH="${VMDIR}/${VMNAME}-serial.socket"
+    if [ ! -f "${disk_img}" ]; then
+        cd "${VMPATH}"
+    fi
 
     # Backwards compatibility for ${driver_iso}
     if [ -n "${driver_iso}" ] && [ -z "${fixed_iso}" ]; then
@@ -1745,6 +1814,11 @@ if [ -n "${VM}" ] && [ -e "${VM}" ]; then
     # Backwards compatibility for ${disk} (size)
     if [ -n "${disk}" ]; then
         disk_size="${disk}"
+    fi
+
+    # Set the default disk_format if not provided by user
+    if [ -z "${disk_format}" ]; then
+        disk_format=$(${QEMU_IMG} info "${disk_img}" | grep 'file format' | cut -d ':' -f 2 | tr -cd '[:graph:]')
     fi
 
     if [ -n "${display}" ]; then
@@ -1766,6 +1840,11 @@ if [ -n "${VM}" ] && [ -e "${VM}" ]; then
         VIEWER="${viewer}"
     fi
     viewer_param_check
+
+    if [ -z "${WIDTH}" ] || [ -z "${HEIGHT}" ] ; then
+        WIDTH="${width}"
+        HEIGHT="${height}"
+    fi
 
     # Set the default 3D acceleration.
     if [ -z "${gl}" ]; then
@@ -1887,12 +1966,18 @@ if [ ${VM_UP} -eq 0 ]; then
         sleep 3.5
         monitor_send_cmd "sendkey ret"
     fi
+    if [ -n "${iso}" ] && [ "${guest_os}" == "windows-server" ]; then
+        sleep 7
+        monitor_send_cmd "sendkey ret"
+    fi
     start_viewer
 else
     parse_ports_from_file
     start_viewer
 fi
 
-[ -n "${MONITOR_CMD}" ] && monitor_send_cmd "${MONITOR_CMD}"
+if [ -n "${MONITOR_CMD}" ]; then
+    monitor_send_cmd "${MONITOR_CMD}"
+fi
 
 # vim:tabstop=2:shiftwidth=2:expandtab
