add  additional freespirit runtime alerts to quickEMU

diff --git a/qqX.builtins/freespirit/quickemu b/qqX.builtins/freespirit/quickemu
--- a/qqX.builtins/freespirit/quickemu
+++ b/qqX.builtins/freespirit/quickemu
@@ -1,8 +1,31 @@
 #!/usr/bin/env bash
-# Use qqX C.UTF-8 locale, not:  export LC_ALL=C
 
-if ((BASH_VERSINFO[0] < 4)); then
-    echo "Sorry, you need bash 4.0 or newer to run this script."
+# For qqX use with C.UTF-8 locale, not:  export LC_ALL=C
+# This section enables testing via './quickget --check distroname' from a terminal opened in the built-ins folder:
+if [[ -e "$(pwd)/qqX_quickget_mods" ]]; then
+    if [[ $(pgrep -aAi qqX 2>/dev/null) ]] ; then
+        printf "\n  qqX running elsewhere ... \n\n" ; exit 1
+    else
+        OriginalPATH="$PATH"
+        CurrentFolder="$(pwd)"
+        if [[ -e "/usr/share/qqX/qqX.lib/fv" ]]; then qqX_LibraryFolder="/usr/share/qqX/qqX.lib"
+        else printf "\n  qqX libraries not found .... \n\n" ; exit 1
+        fi
+        export PATH="$CurrentFolder:${qqX_LibraryFolder}:${OriginalPATH}"
+        if  grep -sqi 'C.utf8' <<< "$(locale -a)"; then export "LC_NUMERIC=C.UTF-8" ; export "LC_COLLATE=C.UTF-8"
+        else export "LC_NUMERIC=C" ; export "LC_COLLATE=C"
+        fi
+    fi
+elif [[ "$PATH" != *'qqX'* ]]; then
+    printf "\n  This individual code branch is intended to be run as a qqX built-in."
+    printf "\n\n  qqX mod files and libraries have not been found ... ?"
+    printf "\n\n  If running from a cloned Quickemu fork, you need to switch branches"
+    printf "\n  or need to download qqX and run from a terminal opened in the FreeSpirit folder. \n\n"
+    exit 1
+fi
+
+if ((BASH_VERSINFO[0] < 5)); then
+    echo "Sorry, you need bash 5.0 + or newer to run this script."
     exit 1
 fi
 
