add  some more dependency checks

diff --git a/qqX.system/qqX_system_install b/qqX.system/qqX_system_install
--- a/qqX.system/qqX_system_install
+++ b/qqX.system/qqX_system_install
@@ -151,27 +151,31 @@ if [[ ! $HideFHSwarnings ]] &&  [[ ! $(type -p bc) ]]; then
   [[ $FHS_Alert ]] &&  exit 
 fi
 
-##  Check for 'curl' as not in all distros (where $1 test is true if command line is being used) 
+##  Check for items sometimes missing 
 if [[ ! $(type -p curl) ]]; then
   printf "\n\n  'Curl' is a listed dependency of QuickEmu and is also used by qqX ...\n\n"
   if [[ $1 ]]; then exit 1 ; else read -rp "  [enter] to ignore or continue > " ; fi
 fi
-##  Check for 'jq' as not in all distros (where $1 test is true if command line is being used) 
 if [[ ! $(type -p jq) ]]; then
   printf "\n\n  'jq' is a listed dependency of QuickEmu ...\n\n"
   if [[ $1 ]]; then exit 1 ; else read -rp "  [enter] to ignore or continue > " ; fi
 fi
-##  Check for 'bc' as not in all distros (where $1 test is true if command line is being used) 
 if [[ ! $(type -p bc) ]]; then
   printf "\n\n  A 'bc' installation should normally be present and is required by qqX ...\n\n"
   if [[ $1 ]]; then exit 1 ; else read -rp "  [enter] to ignore or continue > " ; fi
 fi
-##  Check for 'wget' as not in all distros (where $1 test is true if command line is being used) 
+if [[ ! $(type -p xrandr) ]]; then
+  printf "\n\n  An 'xrandr' installation should normally be present and is required by qqX ...\n\n"
+  if [[ $1 ]]; then exit 1 ; else read -rp "  [enter] to ignore or continue > " ; fi
+fi
 if [[ ! $(type -p wget) ]]; then
   printf "\n\n  A 'wget' installation should normally be present and is needed in certain places ...\n\n"
   if [[ $1 ]]; then exit 1 ; else read -rp "  [enter] to ignore or continue > " ; fi
 fi
-
+if [[ ! $(type -p 7z) ]]; then
+  printf "\n\n  A '7zip' installation should be present and is needed in few places ...\n\n"
+  if [[ $1 ]]; then exit 1 ; else read -rp "  [enter] to ignore or continue > " ; fi
+fi
 if [[ ! $(type -p spicy) ]]; then
   printf "\n\n  Check for 'spice' installations 'spicy', 'spice-vdagent' and 'spice-gtk'/'spice-client-gtk' ...\n\n"
   if [[ $1 ]]; then exit 1 ; else read -rp "  [enter] to ignore or continue > " ; fi
